src/components/Form/HelpMessage/index.tsx, src/components/Form/Label/index.tsx, src/components/Form/TextInput/index.tsx, src/components/TextInput/index.tsx
- close #9
- 텍스트 입력을 목적으로 할 `TextInput` 컴포넌트를 추가했습니다.
- `Label`, `HelpMessage` 등 다른 입력 컴포넌트에서도 사용할 수 있는 UI는 별도로 분리했습니다. 
- 나중에 react-hook-form에서 사용할 수 있게 ref를 expose 해주었습니다.
=> 텍스트 입력 컴포넌트 추가

src/components/Form/Select/OptionItem/index.tsx, src/components/Form/Select/index.tsx
- 원래 object로 valule 바인딩해도 잘 동작해야 할텐데,, 그게 안되서 string value를 바인딩합니다.
=> Select 박스에서 선택된 값이 하이라이팅 안되는 이슈 수정

package.json, pages/edit/index.tsx, src/api/group.ts, src/components/Form/ErrorMessage/index.tsx, src/components/Form/FileInput/index.tsx, src/components/Form/Presentation/index.tsx, src/components/Form/Select/index.tsx, src/components/Form/TextInput/index.tsx, src/components/Form/Textarea/index.tsx, src/types/form.ts, yarn.lock
- close #42 
- `schema`에는 메시지 추가가 전부에요. 날짜 필드에 한해서 포맷 관련 validation을 적용하기 위해 `z.refine()` 를 사용했어요.
- `Presentation` 에서 `FormController`의 render function이 `fieldState`, `formState`를 내려주고 있는데, 여기서 `error`를 가져와 입력 필드로 내려주도록 했어요.
https://user-images.githubusercontent.com/31213226/202913088-22c30b61-c058-42e5-a47c-31f01db3fbaf.mov
=> 모임 생성/수정 폼 validation 추가 및 날짜 포맷 수정

pages/_app.tsx, src/api/auth/index.ts, src/api/index.ts, src/hooks/useAuth.ts
- close #89 
- playground 로그인 할때 받은 토큰은 playground API를 찌르는 instance의 헤더에 저장하고, 이 토큰으로 crew 서비스에 한번 더 로그인해서 crew token을 발급받습니다. 이 crew token은 crew API를 찌르는 instance의 헤더에 저장됩니다.
- 토큰이 없으면 로그인 페이지로 redirect 됩니다.
=> Crew API 서버에서 제공하는 로그인 API 연동

src/hooks/useAuth.ts
- close #102 
- localStorage에서 playground 토큰을 불러와 api header에 설정하는 타이밍을 앞당겼습니다(기존에는 crew `/auth` API를 호출한 다음에 crew token과 함께 설정됐음.)
=> Playground API token 설정 타이밍 수정

src/hooks/useAuth.ts
- close #105 
- 토큰 state를 이전 state를 바탕으로 새롭게 설정하는 로직에 오류가 있어서 이를 수정합니다.
=> 토큰 state가 싱크 안 맞는 이슈 수정

pages/edit/index.tsx, src/api/group.ts
=> 모임 수정 안되는 버그 수정

src/components/form/Presentation/index.tsx
- close #123 
- 이제 ⬇️버튼 눌러도 숫자가 마이너스까지 안 내려갑니다.
- 숫자 입력했다가 지워도 0이 안 남는 거 확인했습니다!
=> 모집 인원 숫자 입력한 뒤 지울 때 0이 남는 이슈 해결

pages/detail/index.tsx, src/components/page/groupDetail/DetailHeader.tsx, src/components/page/groupList/Card/index.tsx, src/components/page/groupManagement/ItemDescriptionBox.tsx, src/components/page/groupManagement/ManagementListItem.tsx, src/utils/date.ts
- close #142 
- 저번 회의에서 결정한 대로 dateFormat, timeFormat 함수 대신 dayjs를 사용했습니다.
이제 두 함수가 필요 없어서 date.ts를 제거했습니다!
- 데스크탑
- 모바일
=> 모임 참여자 시간 정보 추가

src/components/page/groupList/Filter/Search/index.tsx, src/components/page/groupList/Filter/index.tsx
- close #150 
- `href`에 들어갈 노션 링크는 아직 전달받지 못해서 나중에 추가하도록 하겠습니다!
- 모바일
- 데스크탑
=> 모임 신청 가이드 버튼 추가

pages/edit/index.tsx, pages/make/index.tsx
- close #159 
- 리액트 쿼리를 공통적으로 적용하는 리팩토링을 했습니다.
=> 모임 생성 / 수정 페이지 react-query 적용

src/components/button/Switch.tsx, src/components/form/FormSwitch/FormSwitch.tsx, src/components/form/Presentation/index.tsx, src/types/form.ts
- close #185 
https://user-images.githubusercontent.com/31213226/226163945-c7f7be21-d9ff-40f3-9b23-4f05a45a557b.mov
=> 모임 생성 / 수정 폼에 대상 기수 입력 필드 추가

pages/edit/index.tsx, src/api/meeting/index.ts, src/components/form/Presentation/index.tsx, src/data/options.ts, src/types/form.ts
- close #181 #187 #195 
https://user-images.githubusercontent.com/31213226/226677901-8524f3d4-c5d4-42d2-bea2-a77def680b8d.mov
=> 모임 생성 / 수정 '멘토 구해요', '대상 기수', '대상 파트' API 연동

src/components/form/FormController/index.tsx, src/components/form/Presentation/index.tsx
- close #215 
- 이슈의 원인은 기본값이 undefined 여서 폼이 not valid 하다고 판단했기 때문에 발생했음
- 그래서 체크박스 디폴트 값을 `false` 로 부여했지만, 여전히 동작하지 않았고, 조사 결과 라이브러리 Github 레포에 이슈가 올라와있었음(링크: https://github.com/react-hook-form/react-hook-form/issues/7337#issuecomment-999275751)
- 해당 이슈에서 메인테이너가 안내하는 해결 방법을 적용함(`defaultValue`가 `false` 라면 `setValue()` 메서드로 값을 설정하는 이펙트 추가)
=> 모임 생성 시 체크박스 필드('대상 기수', '멘토 구해요')에 한번 체크해야 제출 버튼 활성화 되는 이슈 수정

src/types/form.ts
- close #229 
- 사파리 브라우저가 `Date()` 파싱 잘 못하는 버그가 있었습니다.
- 그래서 관련 이슈가 dayjs에도 올라와 있었고, 해당 [이슈](https://github.com/iamkun/dayjs/issues/1822)에서 제안하는 [솔루션](https://github.com/iamkun/dayjs/issues/1822#issuecomment-1082731428)을 적용했습니다(커스텀 플러그인 사용)
=> Safari에서 날짜 입력 시 에러나는 버그 수정

pages/detail/index.tsx
- close #244 
- 정규 표현식 urlRegex를 사용해 content에서 url을 찾는 방식으로 구현했습니다.
|Before|After|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/58380158/227838722-ec982e48-8851-4476-b4c9-da4b65361632.png)|![image](https://user-images.githubusercontent.com/58380158/227838648-1d32bdec-99fb-4d6d-b843-5840fe194ffa.png)|
=> 텍스트를 클릭 가능한 링크로 변환하기

src/components/form/Textarea/index.tsx
- close #222 
OS나 텍스트 에디터에 따라 줄바꿈 문자가 다르게 인코딩될 수도 있다고 합니다.
예를 들어 윈도우에서는 `\r\n`으로 인코딩 되는데, 이때 `\r`과 `\n`이 각각 하나의 글자로 계산됩니다.
따라서 줄바꿈 문자를 `\n`으로 통일하고, 이를 하나의 글자로 계산하도록 처리했습니다.
|Before|After|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/58380158/227884533-2d31aa75-8d05-459b-b580-3cecfb2f6611.png)|![image](https://user-images.githubusercontent.com/58380158/227884662-95325720-b35e-4cdb-b36c-15bc9aeca84c.png)|
=> 모임 수정 시 글자 수 300자 제한 관련 이슈 해결

src/components/page/meetingDetail/DetailHeader.tsx, src/components/page/meetingManagement/MeetingInformation.tsx
- close #250 
- 요구사항이 계속 수정되어 불필요한 커밋이 많습니다..🥹 **결국 백엔드에서 처리하기로 해서 로직 변경사항은 없습니다.**
- ERecruitmentStatus 써야 하는데 EApprovalStatus 쓰고 있는 부분이 있어서 수정했습니다.
https://user-images.githubusercontent.com/58380158/228159333-1c332fcb-4cf7-4bb4-9820-9cd845a6d3a6.mp4
=> 모집 정책 관련 임시 변경

src/components/page/meetingList/Pagination.tsx
- close #256 
- 만약 전의 로직이라면 마지막 페이지가 7페이지라고 했을떄, 4에서 누르면 페이지가 9로 이동하게 되는 오류가 생각났어요. 
- 그래서 다음 pagebundle의 첫번째로 이동하도록 만들었어요
- 마찬가지로 prevBundle 함수도 전 pagebundle의 마지막으로 이동하게 만들었어요.
=> pagination moveBundle 로직 수정

src/components/util/auth.ts
- close #274 
- 프로필을 추후에 작성하는 유저의 정보를 정상적으로 반영하기 위해 변경
=> 크루 토큰을 로컬 스토리지에 저장하지 않도록 수정

src/components/page/meetingDetail/ApplicationModalContent.tsx, src/components/page/meetingDetail/DetailHeader.tsx
- close #278 
- 중복으로 신청하는 이슈가 인입되어 이를 수정합니다.
=> 모임 신청하기 따닥 방지

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml, package.json, yarn.lock
- close #265 
- next-on-pages는 edge runtime을 지원하기 위해 부가적인 작업을 수행해주는데, 우리의 경우는 이게 불필요하기 떄문에 단순히 export 시켜 이를 pages에 배포하도록 수정합니다. 이로 인해 빌드 속도를 개선할 수 있습니다.
=> CI환경 빌드 커맨드 수정으로 빌드 시간 오래걸리는 것 개선

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml
- `sopt-crew-dev` cf pages가 현재 preview로만 동작하고 있어서, production 환경으로 배포할 수 있도록 수정합니다.([관련 내용](https://community.cloudflare.com/t/pages-direct-upload-cant-set-the-production-branch-name/402072/3))
- next export 로 빌드 명령을 변경한 것이 잘 반영되어 배포될 수 있도록 배포 액션을 수정합니다.
=> 개발 환경 배포 액션 수정

pages/detail/index.tsx, src/components/page/meetingDetail/Carousel.tsx, src/components/page/meetingDetail/FeedPanel.tsx, src/components/page/meetingDetail/InformationPanel.tsx, src/components/tabList/TabList.tsx
- close #345 
- 기존에는 `pages/detail/index.tsx`에 모임 안내 내용이 들어갔는데,
피드 탭과 모임 안내 탭이 각각 생기면서
피드 내용은 `src/components/page/meetingDetail/FeedPanel.tsx`로
모임 안내 내용은 `src/components/page/meetingDetail/InformationPanel.tsx`로 분리했습니다.
|데스크탑|모바일|
|:-:|:-:|
|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/be8de148-bff6-4458-849d-436c0bf70208)|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/133bd0c8-2897-4039-a8d9-e1c958e5a021)|
=> 피드, 모임 안내 탭 추가

src/components/avatar/Avatar.stories.ts, src/components/avatar/Avatar.tsx, src/components/avatar/AvatarGroup.stories.tsx, src/components/avatar/AvatarGroup.tsx
- close #347 
- 단일 아바타 컴포넌트는 그냥 동그란 이미지 컴포넌트입니다. 이름, 몇 시간 전 수정 등 메타 정보들은 사용하는 쪽에서 자유롭게 추가하도록 합니다(인터페이스를 따로 뚫진 않았어요. 그게 더 복잡할 것 같아서)
- 그룹 아바타 컴포넌트는 아바타 컴포넌트들을 자식으로 갖습니다. 
```tsx
<AvatarGroup>
<Avatar src="https://mui.com/static/images/avatar/1.jpg" alt="sample iamge" />
<Avatar src="https://mui.com/static/images/avatar/2.jpg" alt="sample iamge" />
<Avatar src="https://mui.com/static/images/avatar/3.jpg" alt="sample iamge" />
</AvatarGroup>
```
- 인터페이스는 [MUI](https://mui.com/material-ui/react-avatar/)를 참고했어요.
=> 아바타 컴포넌트 구현

src/components/filter/MultiSelect/index.tsx, src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx, src/components/form/Select/BottomSheetSelect/BottomSheetDialog.tsx, src/components/form/Select/Button/index.tsx, src/components/form/Select/index.tsx, src/components/form/TableOfContents/index.tsx, src/components/page/meetingList/Card/ManagementButton.tsx, src/components/page/meetingList/Filter/Modal/OpenButton.tsx, src/components/page/meetingList/Filter/Search/index.tsx, styles/globals.css
- close #388 
- 원래 Box 컴포넌트에만 있던 속성을 일괄로 적용했어요
- 처음에는 box 컴포넌트를 활용해서 부분적으로만 적용하자는 생각이었어요.
- 하지만 저희가 stitches가 아닌 다른 라이브러리를 사용하게 되었을때 이부분이 많이 헷갈려할것 같았어요.
- 일단 제가 눈에 보이는 부분은 전부 교체를 하였어요.
- 단, tablet 환경에서부터 모바일 버전으로 보여주자는 이야기를 했어서, 약간 다를 수 있어요
- 추가적으로 Select 컴포넌트들의 tablet 환경에서 bottomSheet가 안나오는 에러를 해결했어요. ( 아무도 안썻나봐요.)
- 그리고 bottomSheet에 overlay를 적용해서 세세한 오류를 잡았어요. 
크린샷
=> boxSizing:border-box 일괄 적용 작업

next.config.js, src/types/svg.d.ts
이렇게 해서 크기를 수정할 수 있어요
```tsx
import CheckedIconV2 from '@assets/svg/icon_progress_checked.svg?v2';
const Foo = () => <CheckedIconV2 width={24} height={24} />;
```
```tsx
import CheckedIconV2 from '@assets/svg/icon_progress_checked.svg?v2';
const ScalableCheckedIconV2 = styled(CheckedIconV2, {
width: '24px',
height: '24px',
});
const Foo = () => <ScalableCheckedIconV2 />;
```
=> SVG 크기 설정을 위한 next.config.js 수정

src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts, src/components/feed/FeedPostViewer/FeedPostViewer.tsx
=> 피드 상세 뷰 이미지 영역 추가

.storybook/preview.tsx, package.json, src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts, src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/components/modal/ImageCarouselModal.tsx, yarn.lock
- close #406 
- 나중에 캐러셀을 공통으로 사용할 수 있게 된다면 모달과 캐러셀을 분리할 수 있겠단 생각이 들었어요.
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/592acb4a-8e02-47ab-bfb0-ab89f82f9a7e
=> 피드 상세 뷰 이미지 캐러셀 UI 추가

src/components/avatar/Avatar.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.tsx
- close #394 
- @tablet 을 이용해서 모바일뷰 대응했습니다!
=> 피드 상세 content 부분 모바일 대응

src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/components/modal/ImageCarouselModal.tsx
=> 피드 상세 뷰 이미지 영역 및 캐러셀 반응형 디자인 추가

pages/post/index.tsx
=> 피드 상세 뷰 게시글 조회 API 연동

src/components/feed/FeedPostViewer/FeedPostViewer.tsx
=> 피드 상세 뷰 게시글 작성 시간 포맷 수정

package.json, pages/detail/index.tsx, src/components/button/Switch.tsx, yarn.lock
- close #433 
- 플그 헤더 버전 올리니까 에러가 뜸
- 이거 플그측에서 해결해줘야할것 같은데 그것만 해주세여....
+ 준호가 해결해줌 !
=> 주말 아침부터 보라빛 향기

pages/detail/index.tsx, src/components/page/meetingDetail/Feed/EmptyView.tsx, src/components/page/meetingDetail/Feed/FeedPanel.tsx
- 프로덕션 배포를 위해 버튼을 잠시 없애고, 모임 안내 탭을 기본으로 설정했어요.
=> 피드 작성 버튼 임시 제거 및 주석 처리

src/components/page/meetingList/Card/MobileSize/CardType.tsx
- 아래 스크린샷처럼 카드가 밀려 보이지 않도록 title에 minHeight를 설정했어요.
=> 제목 minHeight 설정

src/components/avatar/Avatar.tsx, src/components/page/meetingDetail/Feed/FeedItem.tsx, src/constants/feed.ts, src/constants/index.ts, src/utils/truncateText.ts, stitches.config.ts
- close #411 
- 글자 수를 기준으로 말줄임 처리가 필요한 경우, utils에 있는 `truncateText`를 활용해 주세요 😉
- 프사가 없는 경우를 대비해 Avatar.tsx에 `<ProfileDefaultIcon />`을 추가했어요.
- 이번 릴리즈에는 수정/삭제 기능이 포함되지 않아 더보기 버튼을 숨겼어요.
=> 모임 피드 아이템 보완

package.json, pages/_app.tsx, pages/post/index.tsx, src/api/index.ts, src/components/util/auth.ts, src/stores/tokenStore.ts, yarn.lock
=> 인증토큰 적용 방법 수정 및 opanapi-fetch 가 codegen 한 api 클라이언트에 인증 토큰 적용

pages/post/index.tsx, src/components/feed/FeedCommentInput/FeedCommentInput.tsx, src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/utils/dayjs.ts
- close #439 
- 댓글 개수 & 좋아요 버튼 영역에서 댓글 개수 보여주려면 commentCount 이런 props interface 추가해주어야 하는데, 그것 보단 그냥 이 섹션을 합성할 수 있게 하는게 좋을 것 같아 해당 작업 PR 추가 예정
=> 피드 상세 페이지 댓글 목록 조회 API 연동

pages/post/index.tsx, src/hooks/useComment.ts
- close #453 
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/83c25f04-07e9-4101-876a-5faa224eb7a4
=> 피드 상세 뷰 댓글 목록 무한스크롤 적용

src/api/post/index.ts
=> 피드 목록 조회 API 인증 안되는 이슈 수정

package.json, pages/detail/index.tsx, src/api/post/hooks.ts, src/components/page/meetingDetail/Feed/EmptyView.tsx, src/components/page/meetingDetail/Feed/FeedItem.tsx, src/components/page/meetingDetail/Feed/FeedPanel.tsx, src/constants/feed.ts, yarn.lock
- close #448 
- 피드 개수는 `useInfinitePosts`에서 `total`로 가져왔어요.
- `useInfinitePosts` 수정하면서 `isFetchingNextPage`도 추가하고 전에 미리 만들어둔 스켈레톤도 적용했어요.
- 피드 아이템을 누르면 상세 페이지로 이동하도록 설정했어요.
|데스크탑|모바일|
|:-:|:-:|
|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/6fe9599a-5044-40d3-8b3b-a181ff559d70)|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/15178e93-5f56-48ac-bd73-ef621423cfe0)|
(개수 부분에 있는 텍스트 색깔 변경되어서 지금이랑 달라요! 스크린샷은 구조만 봐주세용)
=> 피드 개수 보여주는 부분 추가

pages/post/index.tsx
=> 피드 상세 뷰 댓글 개수 정확히 보여주도록 수정

src/api/post/hooks.ts, src/api/post/index.ts, src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
- close #460 
1. apiV2 를 사용하고 싶었는데,, apiV2 DELETE 에는 어떤 형식만 들어갈 수 있어서, 댓글 삭제 url 을 넣으니까 입력할 수 없다고 해가지고,, 우선 api 를 이용했습니당 ㅠ^ㅠ
2. CommentList 에서 옵셔널 체이닝 붙여준 건, 댓글이 0개일 때 서버에서 빈 배열을 넘겨주는 게 아니라 undefined 가 될 수도 있어서..! 요건 서버 스앵님들께서 고쳐주시면 바로 고치겠습니당!-!
+++++++
늦은 시간까지 나의 쓸데없는 질문을 받아준,,, 은수 오빠와 지연 언니 고마와,,, + 아빠도 늘 고마와🌷🚀 🌕 
https://github.com/sopt-makers/sopt-crew-frontend/assets/86764406/e6970630-9822-4d82-9ab8-301bfcbda020
=> 댓글 삭제 API 연동

package.json, src/__generated__/schema.d.ts
=> schema generation 스크립트가 리모트 OAS 스펙을 가져오도록 수정

pages/post/index.tsx, src/__generated__/schema.d.ts, src/api/post/hooks.ts, src/components/feed/FeedActionButton/FeedActionButton.tsx, src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx, src/components/feed/FeedCommentEditor/FeedCommentEditor.tsx, src/components/feed/FeedCommentViewer/FeedCommentViewer.stories.ts, src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts, src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/components/feed/Modal/FeedEditModal.tsx, src/components/page/meetingDetail/Feed/FeedPanel.tsx, src/hooks/useComment/useComment.ts, src/hooks/useComment/useCommentMutation.ts
- close #477 
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/67798643-e0b6-4312-80d4-78ecf9b8cd45
=> 댓글 수정 기능 추가

src/utils/dayjs.ts
=> 댓글 작성 시간이 몇초 후 라고 표기되는 버그 수정 및 워딩 변경

pages/post/index.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.tsx
- close #478 
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/c7ff206e-a9c9-4f1d-bd3f-dff0e42e04b0
=> 피드 게시글 삭제 기능 추가

src/components/avatar/AvatarGroup.tsx
=> 아바타 컴포넌트 스타일 수정

src/components/feed/FeedPostViewer/FeedPostViewer.tsx
- close #493 
| Before | After |
|----|-----|
| <img width="805" alt="Screenshot 2023-10-01 at 9 54 44 PM" src="https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/7b200432-cc5a-488a-a53e-a48748c6d04e">  |  <img width="801" alt="Screenshot 2023-10-01 at 9 54 29 PM" src="https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/22915a25-5e01-41b3-b81f-b1e2981f0ff6"> |
=> 피드 상세 뷰 이미지 영역 패딩 수정

src/components/feed/FeedCommentInput/FeedCommentInput.tsx
- close #494 
| Before | After |
|-----|-----|
|  <img width="358" alt="Screenshot 2023-10-01 at 10 23 50 PM" src="https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/6bd04879-717d-400a-8e82-53b2dbfd3d71">  |  <img width="358" alt="Screenshot 2023-10-01 at 10 23 35 PM" src="https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/b34bfc74-f1e9-4840-ba2e-e06094d1be4a">  |
=> 피드 상세 뷰 댓글 입력 UI가 자리차지하는 스타일 이슈 수정

src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/components/page/meetingDetail/Feed/FeedItem.tsx
=> [이슈 02] 단락을 나누어 글을 작성했는데 붙어버리는 이슈 발생 

src/components/page/meetingDetail/Feed/FeedPanel.tsx
=> [이슈 04] 피드 리스트 뷰 MO와 PC 작성하기 CTA 버튼 색상 상이(주황색으로 통일)

src/components/page/meetingDetail/DetailHeader.tsx
=> [이슈 11] 모집 마감 태그 컬러 상이

src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
- close #517 
wordBreak 기본값이 Normal 인데 이 경우 영어는 줄바꿈이 안 된다고 해서 break-all 로 바꾸어주었습니다!
=> [이슈 20] 모바일 뷰 댓글 width 넘어갈 시 줄바꿈 안 되는 현상 해결

pages/post/index.tsx, src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx, src/components/feed/FeedCommentInput/FeedCommentInput.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.tsx
=> 피드 상세 뷰 앰플리튜드 이벤트 로깅

src/components/feed/Modal/FeedCreateModal.tsx, src/components/feed/Modal/FeedEditModal.tsx, src/components/feed/Modal/FeedFormPresentation.tsx, src/utils/dayjs.ts
- close #534 
- 현재 피드 작성 중 이탈 이벤트를 모달이 닫힐 때 로깅하도록 했는데, 현재로선 작성을 정상적으로 완료 후 닫힐때도 로깅됨. 이 이벤트를 이탈을 보기 위해 찍는 것이라면 '피드 작성 버튼' 클릭 이후 또는 작성 모달 조회 이후 작성 완료 이벤트가 얼마나 발생했는지를 보면 로깅하지 않아도 될 듯?
=> 피드 작성 뷰 앰플리튜드 이벤트 로깅

src/components/avatar/Avatar.tsx, src/components/page/meetingDetail/Feed/FeedItem.tsx
- close #537 
- 좋아요시 전체 피드가 리랜더링 되는데, 아바타 이미지가 너무 커서 깜빡이는게 너무 큼. 그래서 아바타 컨포넌트에 getResizedImage 추가해서 조정
=> [이슈 25] 피드 리스트에서 좋아요 클릭 시 다른 곳에서 산발적으로 아바타 컴포넌트가 바뀌는 이슈

src/components/modal/ImageCarouselModal.tsx
- close #564 
- maxHeight가 600px로 지정되어 생기는 문제라 이 부분을 수정했습니다.
|Before|After|
|:-:|:-:|
|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/9936a92f-708c-4210-9c11-7e33b961eb8d)|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/291889b5-2b93-455b-b260-b5c270e690f3)|
=> 모임 상세 이미지 크기 이슈

src/components/feed/FeedPostViewer/FeedPostViewer.tsx
- close #470 
|Before|After|
|:-:|:-:|
|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/a27bf1d5-aada-412e-b4eb-55601c8bab3f)|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/d1cab83b-fedc-40a5-b315-742da586a1e6)|
=> 피드 상세뷰 가로 스크롤 수정

src/components/header/Header.tsx, src/components/util/auth.ts
- close #579 
- 작업 배경은 이슈를 참고해 주세요~!
=> localStorage 대신 sessionStorage 사용

pages/post/index.tsx, src/components/feed/FeedActionButton/FeedActionButton.tsx, src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/hooks/useToast/Toast.tsx
- close #588 
- 신고하고 나서 피드백 주려고 toast를 띄우려고 보니 error 타입만 지정이 가능해서 타입을 확장했어요(`info` 타입 추가)
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/37e3e55a-fb3a-4a4f-a140-af7bdcc43c50
=> 모임 피드 게시글 신고하기 기능 추가

src/components/feed/Modal/FeedFormPresentation.tsx, src/components/feed/Modal/SelectMeeting/index.tsx, src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx, src/components/page/meetingDetail/Feed/FeedPanel.tsx, src/components/page/postList/FloatingButton/index.tsx
- close #609
- 밑에 두개는 디자인쪽에서 들어와서 같이 처리했어여
https://github.com/sopt-makers/sopt-crew-frontend/assets/26538967/dc48c482-c586-4aa5-b134-79251948080a
https://github.com/sopt-makers/sopt-crew-frontend/assets/26538967/aa98934b-61fd-469a-b977-fcedbd34a8e8
https://github.com/sopt-makers/sopt-crew-frontend/assets/26538967/080dc6df-42b0-4d99-9fbe-1def7bad2eee
=> selectMeeting 컴포넌트 모바일 대응

src/components/modal/FloatingButtonModal.tsx, src/components/modal/NoJoinedGroupModal.tsx
=> 내가 속한 모임 없음 모달 UI 작성

src/api/post/hooks.ts, src/components/button/LikeButton.tsx, src/components/page/meetingDetail/Feed/FeedItem/index.tsx, src/components/page/meetingDetail/Feed/FeedPanel.tsx
=> 피드 아이템 컴포넌트 확장(좋아요 버튼 합성, onClick props 추가)

pages/post/index.tsx, src/api/post/hooks.ts
- close #597 
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/38c32772-2610-419f-a5eb-abd19443b20d
=> 피드 게시글 상세페이지에 전체 피드 게시글 목록 UI 추가

pages/post/index.tsx
=> 피드 게시글 상세페이지 스타일 이슈 수정

src/hooks/useScrollRestoration.ts
=> 피드 게시글 상세페이지에서는 스크롤 복원 안되도록 처리

src/api/user/index.ts, src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx, src/components/modal/FloatingButtonModal.tsx, src/components/page/postList/FloatingButton/index.tsx
- close #637 
- 피드 작성되면 플로팅도 꺼져야죠?
=> 피드작성이 안떠요 

pages/post/index.tsx
=> 피드 상세 리스트 뷰 내 카드 width를 핸드오프와 동일하게 수정

src/components/page/meetingDetail/Feed/FeedItem/index.tsx, src/constants/feed.ts
- close #671 
- 기존에는 70자 기준으로 잘랐는데, 3줄 기준으로 자르도록 수정했습니다.
=> 피드 내용 최대 3줄까지 보이도록 설정

pages/index.tsx, src/api/post/hooks.ts, src/components/feed/FeedPostViewer/FeedPostViewer.tsx, src/components/page/meetingDetail/Feed/FeedItem/index.tsx, src/components/page/meetingDetail/Feed/Skeleton/DesktopFeedListSkeleton.tsx
- close #662 
- 현재 Avatar 컴포넌트는 아래와 같습니다.
```typescript
export default function Avatar({ src, alt, sx, className, Overlay }: AvatarProps) {
return (
<SContainer style={sx} className={className}>
{Overlay}
{src ? <SImage src={getResizedImage(src, 32)} alt={alt} /> : <ProfileDefaultIcon />}
</SContainer>
);
}
```
피드 상세 페이지에서는 44 x 44 크기인데 32로 고정되어 있어서 약간 흐릿하게 보이는 것 같습니다.
size도 전달받을 수 있도록 수정하고, 기본 값을 32로 설정하는 건 어떨까요?
```typescript
interface AvatarProps {
src?: string;
size?: number;
alt: string;
sx?: CSSProperties;
className?: string;
Overlay?: React.ReactNode;
}
export default function Avatar({ src, size = 32, alt, sx, className, Overlay }: AvatarProps) {
return (
<SContainer style={sx} className={className}>
{Overlay}
{src ? <SImage src={getResizedImage(src, size)} alt={alt} /> : …
```
=> 필요한 부분에 getResizedImage 적용

src/components/modal/ImageCarouselModal.tsx
- close #678 
|as-is|to-be|
|:-:|:-:|
|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/056fd0d9-dd6e-4d00-9163-05ef7a98aabc)|![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/396773eb-874e-422b-a831-b7af7999228b)|
=> 상단 텍스트와 버튼이 이미지에 가려지는 이슈 해결

src/components/groupBrowsing/mobileSizeCard.stories.ts, src/components/groupBrowsing/mobileSizeCard.tsx, src/components/groupBrowsingSlider/groupBrowsingSlider.stories.ts, src/components/groupBrowsingSlider/groupBrowsingSlider.tsx
- close #682 
정말 그냥 더미 데이터에 UI만 구현했습니다! 
모바일에선 슬라이더가 아닌 기본 가로 스크롤이라 따로 크게 구현할게 없더라구요..?!
=> 모임 둘러보기 모바일 UI 구현

src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx, src/hooks/useThrottle.ts
- close #700 
- 현재 debounce 훅은 작성돼있는데, 디바운스는 마지막 이벤트 발생 시점에서 일정 시간 이후에 함수가 실행되는거라 debounce보다는 일정시간 동안 이벤트를 한번만 실행하는 throttle이 더 적합하다고 생각하여 해당 훅을 만들어서 적용했습니다.
- 5초라는 시간을 임의로 잡긴 했는데(5초 내에 연속으로 다른 피드를 작성할 일이 없을 것 같고 + submit의 비동기함수가 5초 이상 걸릴 것 같진 않아서) 말 그대로 제 피셜이라서... 더 좋은 의견이 있다면 남겨주심 좋을 것 같아요!
=> throttle 사용해서 버튼 중복 클릭 방지

src/components/form/Calendar/index.tsx
- close #769 
- Invalid Date오류였고, 크롬이 아닌 다른 브라우저에서 이슈가 발견된 걸로 보아 크로스 브라우징 이슈일 것이라고 생각했습니다. 검색해보니 이런 글이 있더라구요. [Date 객체 사용 시 주의해야 할 점 (크로스 브라우징 이슈)](https://string.tistory.com/32) 몇가지 데이트 포맷은 크롬이 아닌 다른 브라우저에서는 제대로 작동하지 않고 Invalid Date로 판명될 수 있으니, 공통되는 포맷을 사용해야 한다는 내용의 글입니다..! 해당 글 참고해서 모든 브라우저에서 사용될 수 있게끔 toDate() 메소드를 쓸 때 포맷을 지정해주니 이슈가 해결된걸로 보여요. 하지만 qa는 한 번 더 진행해봐야 할 것 같습니다... 🥺
=> fix: 크로스 브라우징 이슈 해결을 위한 명확한 날짜 포맷 사용

packages/react-mentions/dist/react-mentions.cjs.dev.js, packages/react-mentions/dist/react-mentions.cjs.prod.js, packages/react-mentions/dist/react-mentions.esm.js, src/components/feed/Mention/index.tsx
- close #799 
- 정확한 원인 파악은 실패했으나, 모바일에서 '@누군가' 을 하고, 바로 지우면, '군' 이런 식으로 글자가 남아있는 이슈가 잇었습니다. 왜 모바일에서만 이러는지 모르겠는데, 사파리 크롬 모두 이런 상황이었어요..! 그래서 콘솔을 다 찍어봐도 이건 크로스 브라우징 이슈도 아닌데 왜 이러지.. 싶어서 다른 방법을 찾아봣는데, 멘션을 하고 한 칸을 띄우면, 그 뒤에 지워도 아무 문제가 없더라구요..?? 그래서 멘션 라이브러리에 있는 appendSpaceOnAdd 기능을 가져와서, '@누군가 ' 이렇게 멘션 후 한 칸 띄워주는 식으로 fix 해주었습니다... 
- ++ 테스트에 쓰인 React Mentions 안 콘솔 로그 다 지워주었어요!
- 원인 파악을 제대로 못했기에 후속 조사가 필요해요! 
=> QA: React-Mentions 의 appendSpaceOnAdd 기능으로 모바일에서 멘션 delete 시 글자 남아있는 이슈 해결

packages/react-mentions/dist/react-mentions.cjs.dev.js, packages/react-mentions/dist/react-mentions.cjs.prod.js, packages/react-mentions/dist/react-mentions.esm.js, src/components/feed/Mention/index.tsx
=> QA: 모바일 사파리, 크롬에서 유저 리스트 이상 동작하는 문제 fix + suggestion cursor above 롤백

src/__generated__/schema2.d.ts, src/api/post/hooks.ts
- close #916 
-잘 작동되는 거 확인했습니다!
https://github.com/user-attachments/assets/0e76bad8-9a43-4229-a1e6-99326f9185fe
=> useMutationPostLike type에서 data 제거

src/components/page/meetingDetail/Information/InformationPanel.tsx
=> 모임안내 모집대상 chip QA 반영

src/components/page/meetingDetail/MeetingController/index.tsx
=> 모임 신청 취소하기 다이얼로그 MDS로 교체

package.json, yarn.lock
- close #945 
커피숍 헤더가 생겼다!
노션에 해당 내용 추가도 해두었습니다!
=> @sopt-makers/playground-common 최신버전으로 업데이트

pages/post/index.tsx, src/api/post/hooks.ts, src/api/post/index.ts, src/components/page/meetingList/Advertisement/PostDeleteModal.tsx
=> DELETE, POST, PUT post/v2 API 마이그레이션

packages/react-mentions/src/SuggestionsOverlay.js, pages/_app.tsx, pages/edit/index.tsx, pages/make/index.tsx, src/components/form/FormController/index.tsx, src/components/form/HelpMessage/index.tsx, src/components/form/Presentation/CoLeader/index.tsx, src/components/form/Presentation/index.tsx, src/components/form/SearchMention/SearchMentionContext.tsx, src/components/form/SearchMention/index.tsx, src/components/form/TableOfContents/index.tsx, src/components/page/meetingDetail/MeetingController/index.tsx, src/types/form.ts
- close #936 
공동 모임장 퍼블리싱 작업
- 이해를 돕고자 주석 추가해놓았으니 참고 부탁드립니다.
- 다만 pc에서 모임 개설, 수정에서 공동 모임장 추가의 경우 유저리스트가 뜰 때 약간 모습이 다릅니다.
(react-mention을 사용하기 때문에, 제가 직접 만든 input 틀에 넣어 변경하는 것은 구현이 어려웠습니다.)
- 또한 피그마와 달리 MDS에서의 기본 프로필 모양이 조금 다릅니다. 
- coLeaders.map is not a function 문제가 계속 일어나서, defaultValue를 설정해주었습니다. 
(Presentation의 전체적인 형식(FormController를 사용하는 형식) 을 따르기 위해서)
https://github.com/user-attachments/assets/b2e94f54-da61-44b8-9111-c5fce0752b98
https://github.com/user-attachments/assets/d78ecc69-d428-4df5-b617-35ff49cf18ae
https://github.com/user-attachments/assets/0cb3731f-e9aa-402d-8c97-cde9d1183915
=> 공동 모임장 UI 퍼블리싱

pages/list/index.tsx, src/api/API_LEGACY/meeting/index.ts, src/components/form/Presentation/CoLeader/index.tsx
- close #948 
공동 모임장에 본인을 추가하여 모임 개설 신청을 할 시에, 서버 측에서 에러를 내도록 구성되어 있습니다.
이를 UX를 보존하며 해결하고자, 공동 모임장에 애초에 추가할 수 없도록 검색이 불가능하게 구현했습니다.
=> 개설자 본인은 공동 모임장 검색이 되지 않도록 구현

src/api/index.ts, src/components/form/Presentation/CoLeader/index.tsx, src/components/form/SearchMention/index.tsx
- close #958 
-  ‘+’ 클릭하여 selected상태일때, 다시 default로 돌아가는 기능 정의 (버튼 다시 클릭하거나, 외부 공간 클릭하거나)
- input:mention에서 enter키를 눌렀을 때 텍스트 색이 파란색이 아닌 흰색으로 되도록 구현
- 멤버 검색 INPUT 커서 전체 노출되도록 구현 (임시, 1번 추가 뒤에는 다시 작아짐)
=> 공동 모임장 QA 반영

src/components/page/detail/Information/constant.tsx
- close #issue_number
- chore 한 수정으로, 서버 응답 데이터에 협의 후 결정 워딩이 포함될 경우에만 '협의 후 결정' 을 출력시키도록 fix 하였습니다.
=> QA: 협의 후 결정 여부에 따른 메시지 출력 여부 결정

src/utils/gtm.ts
- close #1000 
- (영광의 1000번째 이슈네요 ㅎㅎ)
- src/components/util/layout/Flex.tsx 파일에 보면 as any 를 쓰고 있는데요, 이 경우는 라이브러리 충돌 이슈로 any 를 쓰고 잘 관리하는 게 any 를 안 쓰는 것보다 훨씬 복잡도가 낮아지기 때문에 그냥 놔두었어요. 반환하는 값은 jsx 이기 때문에 어차피 any 가 아니라 하나의 함수 내에서만 쓰이는 경우라고 이해해주시면 좋을 것 같습니다!!
=> 필요없는 any 지우기 (any 는 타입스크립트가 아니에요!!)

src/components/form/Flash/index.tsx
=> 번쩍 개설 시 이미지 width 를 고정값으로 변경 (디자인 측 요청사항)

src/components/page/detail/Information/InformationPanel.tsx, src/components/page/detail/Information/constant.tsx
- close #1019 
detailData가 type DetailDataType = GetMeetingResponse | GetFlashByIdResponse; 2가지 타입일 수 있었습니다.
이로 인해, GetMeetingResponse로 추론되는 경우 welcomeMessageTypes는 존재하지 않는 필드가 되어버렸습니다.
단순하게 ?(옵셔널 체이닝)으로 해결할 수 있지만, 코드의 통일성 및 디버깅의 용이성을 위해 타입 가드를 작성했습니다.
=> 모바일 환영태그 안 뜨도록 수정

src/components/feed/Modal/FeedCreateModal.tsx
- close #1039 
```typescript
const mentionedOrgIds = parseMentionedUserIds(formMethods.getValues().contents);
if (mentionedOrgIds.length > 0) {
mutatePostPostWithMention({
postId: res.postId,
orgIds: parseMentionedUserIds(formMethods.getValues().contents),
content: formMethods.getValues().contents,
});
}
```
다음과 같이, mentioned 된 유저 id list 의 길이가 0이 아닐 때는 요청 보내지 않도록 조건문 걸었습니다
=> 피드 개설시, mention bug QA 반영

.github/CODEOWNERS, .github/workflows/AutomaticAssignReviewer.yml, pages/detail/flash/index.tsx, pages/detail/index.tsx, pages/list/index.tsx, src/components/groupBrowsing/Carousel/Carousel.tsx, src/components/groupBrowsingSlider/groupBrowsingSlider.tsx, src/components/page/detail/index.tsx, src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx, src/components/page/list/Card/DesktopSizeCard/index.tsx, src/components/page/list/Card/index.tsx
- close #1043 
flashData와 meetingData가 종속성을 지녀서 발생한 문제였습니다.
컴포넌트 분리를 했어야 했는데, 번쩍 기능을 개발하던 당시 매우 촉박한 개발 기간(1주) 때문에 성능보다는 개발 속도를 내야했던 상황이었던 터라 임시방편으로 하나의 컴포넌트에서 Data만 갈아끼워주는 방식으로 설계하였습니다.
이럴 경우, flash (번쩍) 가 아님에도 아래의 사진과 같이 flash API를 호출하는 문제가 발생합니다. (network 탭에 오류로 찍히는 것들)
해당 data가 번쩍인지 아닌지 확인할 방법이 `meetingData.category` 밖에 없습니다.
그래서 아래와 같이 detail 페이지 들어갈 때 `meetingData.category` 가 번쩍이면 `flash API` 를 호출하고, 번쩍이 아니면 `meetingData` 그대로 사용합니다
즉, `flash` 데이터임에도 `meetingData` 를 호출해야하고 / `meeting` 데이터임에도 불필요하게 `flashData` 가 호출되는 상황이 발생한 것입니다.
이에 대한 해결방안으로는 두가지를 생각했습니다.
1. category만 반환해주는 API 파기
2. url에 `flash` 넣기
[슬랙에서 기서와 논의한 결과](https://sopt-makers.slack.com/archives/C042SGKBFK7/p1738340470898789?thread_ts=1738048008.313079&cid=C042SGKBFK7) 2번 정책으로 결정되었고, 이에 따라 page 폴더에 `/detail/flash` 가 …
=> 불필요한 API 호출 방지를 위한 flash / meeting 컴포넌트 분리

pages/post/index.tsx, src/api/post/hooks.ts, src/api/post/index.ts, src/components/feed/FeedActionsContainer/index.tsx, src/components/feed/Modal/FeedEditModal.tsx, src/components/page/detail/Feed/FeedPanel.tsx, src/components/page/list/Advertisement/index.tsx
- close #1041 
피드 삭제하는 부분 말씀드렸다싶이 postId 에 따라 삭제되는 로직이 없어서 수정했습니다. 
하면서 mutation 로직이 ui 그리는 부분에 직접적으로 구현이 되어 있어서, 어떻게 관리할까 고민하다가
분리 했습니다
내용을 정리하자면,
1. 피드 상세 페이지에서 해당 피드를 삭제하면 모임 페이지로 redirect.
2. 피드 하단에 있는 다른 피드 삭제시 Toast 뜨고, 쿼리 무효화 하도록 수정했습니다 !
과거 크루 선배님이 적어두신 TODO 리펙토링 완입니다 !
FeedActionsContainer 로 렌더링 합니다.
return type 은 ReactNode list 라서, 컴포넌트로 구현하지 못하고 함수 return 으로 구현하였습니다.
```typescript
Actions={FeedActionsContainer({
postId: post.id,
isMine: isMine,
handleDelete: mutateDeletePost,
handleReport: handleConfirmReportPost({ postId: post.id, callback: close }),
overlay: overlay,
})}
```
=> 다음과 같이 선언하면, isMine 값을 가져와서 true 이면 수정/삭제 모달이 뜨고, false 이면 신고 모달이 뜹니다.
다른 QA 로 올라온 사항인데, 해당 브랜치에서 두가지 한번에 처리 했습니다
모임 상세 페이지에 있는 피드 ... (더보기 버튼)을 눌러도 모달이 이렇게 안 뜨는 문제가 있었는데, 해당 문제 해결했습니다
모달이 아예 Actions …
=> 더보기 버튼(⋮) 작동 오류, 피드 삭제 기능 버그 수정 QA

src/components/page/home/HomeCardList/DesktopCard.tsx, src/components/page/list/Card/DesktopSizeCard/index.tsx, src/components/page/list/Card/MobileSize/CardType.tsx, src/components/page/list/Card/MobileSize/ListType.tsx, src/utils/image.ts
- close #1051 
오래된 브랜치여서, 자동 병합 도중에 오류가 있었던 듯 합니다!! 새로운 브랜치 생성해서 cherry pick 으로 필요한 커밋만 가지고 왔습니다!
이미지 리사이저를 시범 적용했어요.
앞으로 봐야 할 과제는, 서버비와 특정 이미지 형식에서 깨지는 이미지가 없는지 등의 요소들이에요
현재 3MB 정도 넘어가는 고용량 이미지는 라이브러리 한계 탓인지, 리사이징이 되지 않고 있어요. 이 경우에는 원본 이미지를 반환토록 하고 있습니다!
그냥 보면 무슨 차이지..? 라고 생각드실 수 있는데, 네트워크 쓰로틀링 걸어놓고 이전과 비교해보면 꽤 큰 차이가 납니다!! 드르륵 거리는 현상이 현저히 줄어들어요!
본 목적은 이미지 리사이징이었는데, 캐싱 기능도 함께 들어가져서 서버비 절약 효과도 부수적으로 있을 것이라 예상해요!
크루팀에서 먼저 적용한 뒤 서버비가 현저히 줄어드는 게 보이고 성능도 나쁘지 않다면, 다른 팀에 수출(?)하는 것도 고려해보겠습니다ㅎㅎ
=> 이미지 리사이저 시범 적용 (병합 오류 해결)

pages/_app.tsx
- close #1079 
- `crewToken` 의 만료기간은 10시간인데, `refresh` 로직이 구현되어있지 않습니다.
- 그렇기에 브라우저를 켜둔 채 10시간이 지나면 새로고침없이는 만료된 토큰 에러가 무한으로 로깅되는 상황입니다.
1. `playgroundToken` 을 `localStorage` 에서 받아옴
1. `playgroundToken` 없으면 login 페이지로 redirect
2. `playgroundToken` 을 이용해 `getCrewToken` API 호출하여 `crewToken` 받아옴
3. 리액트 하이드레이션 에러를 피하기 위해, 해당 과정을 아래와 같이 분기 처리
```
// 리액트 하이드레이션 에러를 피하기 위해 사용. 렌더링에 관여하지 않는 코드여서 if 문으로 분기처리
if (typeof window !== 'undefined') {
setAccessTokens();
}
```
해결 방안으로는 서버 만료기간이 10시간이니까, 클라에서는 9시간을 만료시간으로 잡고 refresh 하는 로직을 추가하는 것을 생각하였습니다. 로직 추가를 어디에 하느냐 하는 option은 아래와 같이 두 가지가 있을 것 같습니다.
1. if문 분기처리
```tsx
// 리액트 하이드레이션 에러를 피하기 위해 사용. 렌더링에 관여하지 않는 코드여서 if 문으로 분기처리
if (typeof window !== 'undefined') {
setAccessTokens();
setInterval(setAccessTokens, 9 * 60 * 60 * 1000); // 9시간마다 토큰 갱신
}
``` …
=> Refresh token 로직 추가

pages/edit/flash/index.tsx, pages/edit/index.tsx, pages/make/flash/index.tsx, pages/make/index.tsx, src/components/form/Presentation/KeywordField/index.tsx, src/types/form.ts
- close #1110 
- keyword MAX_COUNT 초과 시 disabled 적용
- category `Chip` 에 `disabled` 조건을 추가시켰습니다!
- `MAX_KEYWORD_COUNT`도 상수처리해주었습니다!
- click 이벤트 핸들러 render 밖으로 분리
- 지난 번에 `welcomeMessageTagField` 에서 받았던 코드리뷰인데
- 비슷한 구조의 컴포넌트라 동일하게 리뷰 적용했습니다!
- 키워드 선택하지 않았을 때 에러 메세지 출력
- `schema` 에서 `min` 조건 추가하여
- `fieldState: { error }` 를 이용했습니다!
- 조건 추가할 때 `{message}` 속성도 같이 넣어주면, error 발생시 `error.message` 를 가져올 수 있습니다
- SubmitButton diabled 조건 추가
- 기존에는 `isValid` 만 고려해서 disabled 처리해주었더라구요!
- `errors` 랑 `dirty` 도 disabled 조건에 필요한 요소들이어서 추가해주었습니다!
https://github.com/user-attachments/assets/55a00a10-7e21-4495-aebf-368a37e1e34e
=> 모임 키워드화 QA 반영

pages/index.tsx, src/components/GuideButton/index.tsx
- close #1148
키워드 알림 설정 버튼을 -> 가이드 버튼으로 바꾼 작업입니다. 
https://github.com/user-attachments/assets/b3a0c96a-9402-4057-8bda-358d1c2020ef
=> [feat] 모임 홈에는 가이드 버튼이 보이도록

src/components/CrewTab/index.tsx, src/components/KeywordsSettingButton/index.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipContent.tsx, src/components/page/list/AlarmSetting/SettingButton/SettingButton.css.ts, src/components/page/list/AlarmSetting/SettingButton/SettingButton.tsx, src/components/page/list/AlarmSetting/TooltipContent/TooltipContent.tsx
- close #1150
https://github.com/user-attachments/assets/9d1471dd-1a28-4daa-904a-2c97525c2bc3
=> [Feat] 툴팁 모바일 반응형 디자인 수정 요청사항 적용

src/api/auth/index.ts
- close #1161 
**AS-IS**
requetBody { "authToken" : "eydfaf......" }
**TO-BE**
플그 로컬스토리지에 있는 serviceAccessToken을 Authorization Header에 Bearer 형식으로 변경
Authorization: Bearer $#{token}
백엔드 요청사항에 따라 수정해서 올렸습니다.
=> [Hotfix] auth api Token 주입 방식 변경

package.json, pages/edit/flash/index.tsx, pages/edit/index.tsx, pages/make/flash/index.tsx, pages/make/index.tsx, pages/post/index.tsx, src/api/comment/mutation.ts, src/api/meeting/hook.ts, src/api/post/hooks.ts, src/api/post/mutation.ts, src/api/user/hooks.ts, src/api/user/mutation.ts, src/components/FloatingButton/index.tsx, src/components/feed/Modal/FeedCreateModal.tsx, src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx, src/components/feed/Modal/FeedEditModal.tsx, src/components/page/detail/Feed/FeedPanel.tsx, yarn.lock
- close #1168 
- isLoading → isPending
- query/mutation 모두: `isLoading` 대신 `isPending`
- query의 재요청 진행 여부는 그대로 `isFetching`
- useInfiniteQuery: initialPageParam 필수
- `initialPageParam: 1`
- `cacheTime` → `gcTime`로 옵션명 변경
- keepPreviousData 제거
- 대체: `placeholderData: keepPreviousData` 유틸 사용
- invalidateQueries 호출 방식 정규화
- 배열 직접 전달 지양 → 객체 형태로 전달
- 예: `queryClient.invalidateQueries({ queryKey: PostQueryKey.all() })`
- queryOptions/infiniteQueryOptions 도입
- 옵션 팩토리 사용 시 v5에서만 제공. v4 유지 시 직접 객체 리턴 (이 경우 타입 체크가 안 됨 ㅜㅜ) <- 버전업하려는 주 목적
- 상태(status) 문자열 변경
- `'loading'` → `'pending'`
- 중단(Abort) 신호
- v5는 `queryFn` 컨텍스트에 `signal` 제공. `fetch` 사용 시 `signal` 연결 권장
- SSR Hydration 컴포넌트 변경 권장
- `Hydrate` → `HydrationBoundary`(v5 권장 방식)
=> React Query v5로 버전업

src/api/post/PostQueryKey.ts, src/api/post/mutation.ts
일단 해당 좋야요 클릭이 안되는 이슈는 확인한 결과 API 요청 자체를 하지 않는 것으로 확인했어요. `console`위치를 바꿔가면서 디버깅을 해본 결과로는 `onMutate`안에서는 뜨지만, `mutationFn`인 `postPostLike`안에서는 안 찍혔기 때문이에요.
즉,
```tsx
usePostLikeMutation -> useMutation -> onMutate -> postPostLike 
```
헤당 순서대로 코드 실행이 될텐데 `postPostLike`까지 코드 실행이 가지 못하고 `onMutate`에서 이슈가 생겼다는 것으로 판단했어요. 실제로 낙관적 업데이트를 위한 `previousPost`가 `undefined`로 찍히는 것을 확인했고, 한마디로 캐싱된 데이터가 없다는 것인데 그 이유는 피드 게시글(post)의 쿼리키와 `getQueryData`를 할 때의 쿼리키가 다르기 때문이에요. 
따라서 `PostQueryKey.mutate`를 `PostQueryKey.detail`로 수정해서 해결했어요.
<br/>
그리고 해당 mutate가 에러 관련 처리가 안 되어 있어서 추가했어요. 낙관적 업데이트로 UI를 미리 변경한 상태기 때문에 에러가 발생하면 onMutate에서 미리 저장해둔 이전 데이터로 해줬어요.
```tsx
onError: (err, _, context) => {
queryClient.setQueryData(PostQueryKey.detail(+queryId), context?.previousPost);
},
```
<br/> …
=> 모임 게시글 상세 페이지에서 좋아요 클릭 안 되는 이슈 해결

src/shared/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
모임 개설에 있는 `SOPT 공식 일정 확인하기` 툴팁 37기 공식일정 기준으로 변경했습니다~~
=> 모임 개설 SOPT 공식 일정 확인하기 툴팁 37기 공식일정 기준으로 변경

src/domain/home/HomeCardList/DesktopCard.tsx
모임 홈 스터디 카드 제목 타이포그래피 `HEADING_6_18_B`로 수정했습니다!
=> 모임 홈 스터디 카드 제목 타이포그래피 수정

package.json, pages/_app.tsx, pages/mine/management/index.tsx, src/api/meeting/MeetingQueryKey.ts, src/api/meeting/mutation.ts, src/api/meeting/query.ts, src/domain/mine/management/ManagementForHost/ManagementListItemForHost.tsx, yarn.lock
query key 리팩토링 하는 과정에서 필터링/정렬에 사용되는 params가 query key에 제대로 들어가지 않는 문제가 있었습니다.
그래서 params이 다른 query들이 같은 key를 갖고 캐싱되면서 필터링/정렬/페이지네이션이 동작하지않았습니다.
모두 수정했고, 수정하는 과정에서 tanstack query devtools도 추가해뒀습니다.
(이슈 분리해서 작업했으면 좋았겠지만,,, 귀찮음 + 시간 이슈로 그냥 요기서 처리했습니다 ㅎㅎ..)
+ 추가로
`management.meta?.pageCount > 0` 요 부분이 데이터가 없으면 아예 필터 + 리스트 + 페이지네이션을 다 안나오게 하고 있어서 지웠습니다.
(필터링 하다가 데이터가 없어지면, 그냥 화면이 없어져버리는 이슈가,,)
https://github.com/user-attachments/assets/d9db3805-a79c-4872-afb6-49c195a77736
=> 신청자 리스트 필터링/정렬/페이지네이션 오류 수정

src/data/options.ts
처음 신청한 사람이 1번이 되도록 수정
신청 `모달`과, `리스트`의 정렬 방식이 달라서 통일했습니다.
=> 신청자 리스트 정렬 오류 수정

pages/_app.tsx, pages/index.tsx, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/api/index.ts, src/constant/environment.ts, src/constant/url.ts, src/domain/home/HomeCardList/CardList.tsx, src/domain/home/HomeCardList/DesktopCard.tsx, src/domain/home/HomeCardList/index.tsx, stitches.config.ts
- 841px ~ 1259px 구간에서 editable 컨텐츠 영역이 짤리고, 스크롤도 안되는 문제가 있었습니다.
- 좌우 스크롤 추가했습니다.
- 작업하면서 isProduction 변수가 필요해서 추가하고, 프로젝트 전체에 사용되는 부분 반영했습니다.
- 홈화면 맨 밑으로 내리면 피드를 계속 다시 불러오는 레거시 코드 삭제했습니다.
https://github.com/user-attachments/assets/e14d6880-2c3d-4087-9ed0-4864926bf73d
=> Home 레이아웃 리팩토링
