pages/group/make/[id]/edit/index.tsx
pages/group/make/index.tsx

- close #7 
- 모임 생성 페이지는 `/group/make`, 모임 수정(삭제) 페이지는 `/group/[id]/edit` 으로 라우트를 생성하였습니다.

모임 생성/수정(삭제) 페이지 라우트 추가

---

package.json
pages/make/index.tsx
src/api/group.ts
src/api/index.ts
src/components/Form/Presentation/index.tsx
src/components/Form/TableOfContents/index.tsx
src/types/form.ts
yarn.lock

모임 생성 페이지에서 모임 생성 API 연동

---

.github/workflows/deploy-development.yml
.github/workflows/deploy-production.yml
package.json
yarn.lock

- close #36
Cloudflare Pages에 배포하는 액션 2개를 추가했어요!
배포에 사용되는 Secret 값들은 다음과 같아요.
`CLOUDFLARE_ACCOUNT_ID`와`CLOUDFLARE_API_TOKEN`은 Organization 단에서 공유해 사용할 수 있도록 Organization secrets 에 등록시켜 놨어요.
`CLOUDFLARE_PAGES_PROJECT_NAME`하고 `PROJECT_ENV`는 배포 환경에 따라 다르게 적용할 수 있도록 Environment 에서 설정할 수 있도록 해놓았어요.
현재 `CLOUDFLARE_PAGES_PROJECT_NAME` 의 값은 production 에선 `sopt-crew`로 되어있고, development 에선 `sopt-crew-dev`로 되어있어요. PROJECT_ENV 은 아직 env 값이 없는 것 같아서 빈칸으로 설정했어요.

chore: 배포 Action 추가

---

pages/make/index.tsx
src/api/group.ts

모임 생성 후 생성된 모임 상세 페이지로 이동

---

src/components/page/groupDetail/Carousel.tsx
src/components/page/groupDetail/NextArrow.tsx
stitches.config.ts

- close #76 
- 로직 수정은 없고, 스타일링 작업만 했습니다.
https://user-images.githubusercontent.com/58380158/209091444-ca1364be-3112-463f-8e46-5867d8163993.mp4

모임 상세 페이지 캐러셀 반응형 작업

---

src/hooks/useAuth.ts

인증 토큰 scheme 빠진 것 수정

---

src/components/header/Header.tsx

- close #i86
- 하.. 기본 폰트 색깔 흰색으로 첨부터 지정할껄

헤더 user name 수정 및 logout 연동

---

src/components/header/Header.tsx

모임개설을 막고 있는 헤더의 무언가 고치기

---

src/hooks/useAuth.ts

Crew API 인증 토큰에 빠진 auth scheme 추가

---

pages/make/index.tsx
src/api/group.ts

모임 생성 후 잘못된 경로로 이동하는 버그 수정

---

src/components/page/groupList/EmptyView.tsx
src/components/page/groupList/Filter/Result/InitializationButton.tsx
src/components/page/groupList/Filter/Result/ResultItem.tsx
src/components/page/groupList/Filter/Result/index.tsx
src/components/page/groupList/Filter/index.tsx

- close #118 
- 지연이가 꼼꼼해서 다행히 잡을 수 있었습니다.

필터 및 검색 결과에 대한 반응형 미흡한 부분 수정

---

pages/make/index.tsx
src/components/form/Presentation/index.tsx
src/components/form/TableOfContents/index.tsx
styles/globals.css

- close #121
- 모임 생성하기 페이지에 피그마랑 다른 부분이 있어서 반영했습니다!
|Before|After|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/58380158/219842763-f3779047-bdec-4b6f-a808-01f6b995f82a.png" width="400" />|<img src="https://user-images.githubusercontent.com/58380158/219842740-b7e384ea-b9f8-4984-b4d3-36369a5f5ffb.png" width="400" />|

모임 생성하기 페이지 TableOfContents 수정

---

pages/make/index.tsx
src/components/form/Presentation/index.tsx

- close #125 
- 상태(isSubmitting)를 추가해 버튼의 disabled 속성을 설정했습니다.
https://user-images.githubusercontent.com/58380158/219868291-a2917ca8-6ecd-4d6d-b4c5-43d0fbec403a.mp4

모임 생성하기 버튼 더블클릭 시 모임 2개 생기는 이슈 해결

---

shim-svg.d.ts
src/types/svg.d.ts

- close #158 
- 흩어진 타입 정의 파일 통합

type definition 파일 위치 통일

---

pages/mine/management/index.tsx
src/components/page/meetingList/Filter/Result/InitializationButton.tsx

- close #169 
- 초대하기 기능을 이번 스프린트에서 잠시 없애기로 해서 주석 처리했습니다.

초대하기 버튼 숨기기

---

src/components/page/meetingManagement/ItemDescriptionBox.tsx
src/components/page/meetingManagement/ManagementListItem.tsx

- close #175 
- 버튼 눌렀을 때 로딩 방식을 다른 페이지랑 통일하기 위해서 바꿨습니다.
https://user-images.githubusercontent.com/58380158/225530759-ba6c3387-641e-4dd4-88c9-8da068d8ad8b.mp4

모임 관리 페이지 로딩 처리 개선

---

src/components/button/Switch.tsx

Switch 컴포넌트 추가

---

pages/detail/index.tsx
src/api/meeting/index.ts
src/api/members/type.ts
src/components/modal/ConfirmModal.tsx
src/components/page/meetingDetail/ApplicationModalContent.tsx
src/components/page/meetingDetail/DetailHeader.tsx
src/components/page/meetingDetail/GuestConfirmModal.tsx
src/components/page/meetingDetail/HostConfirmModal.tsx
src/components/page/meetingDetail/MentorTooltip.tsx
src/components/page/meetingDetail/ProfileConfirmModal.tsx
src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
src/components/page/meetingManagement/ManagementListItem.tsx
src/constants/font.ts
src/constants/option.ts
stitches.config.ts

- close #177 
- 기존 `ConfirmModal`은 `message`가 전부 한 줄짜리 텍스트라 몰랐는데, 이번에 두 줄짜리 넣어보니까 스타일링 깨지길래 같이 수정했습니다.

프로필 없는 유저가 모임 신청하는 경우 처리

---

src/components/form/TableOfContents/index.tsx

모임 생성 / 수정 시 '대상 파트' 선택 안할 경우 table of content 에서 체크박스 해제

---

.github/workflows/deploy-development.yml
.github/workflows/deploy-production.yml
src/api/index.ts
src/components/header/Header.tsx
src/components/page/meetingList/Card/index.tsx
src/hooks/useAuth.ts

프로덕션 배포 (모임기간과 모집기간 또 헷갈려서 수정)

---

.github/workflows/deploy-production.yml
pages/detail/index.tsx
src/components/page/meetingDetail/DetailHeader.tsx
src/components/page/meetingDetail/RecruitmentStatusList.tsx
src/components/page/meetingList/Card/index.tsx
src/components/page/meetingList/Pagination.tsx
src/components/page/meetingManagement/ManagementListItem.tsx

자잘한 수정사항 반영

---

pages/detail/index.tsx
src/components/form/Presentation/index.tsx
src/components/page/meetingList/Card/index.tsx
src/types/form.ts

chore: 모임 기간 => 활동 기간

---

pages/edit/index.tsx

- close #227 
- 수정 페이지에서 빈 폼이 보여지는 이슈는, 이미지 처리 비동기 로직을 await 하느라 그런 것
- 해당 로직을 기다리지 않고 일단 폼 필드를 모두 채우고, 이미지 비동기 처리 로직을 수행해 폼이 비어있지 않도록 수정

모임 수정 페이지에서 폼이 비어있는 이슈 수정

---

src/components/page/meetingDetail/DetailHeader.tsx

모집 대상에 따른 모임 신청 버튼 처리

---

src/components/form/Presentation/index.tsx
src/types/form.ts

- close #232 
- 에러 메시지가 서로 다른 필드에 의해 결정되어야 해서 FormController가 다른 FormController를 품도록 구조 변경

모임 생성 / 수정 페이지 모집 대상 에러 메시지 수정

---

src/components/form/Select/BaseSelect/BaseSelect.tsx
src/components/form/Select/BottomSheetSelect/BottomSheetSelect.tsx

구버전 사파리에서 셀렉트박스 선택 안되는 이슈 수정

---

pages/_app.tsx
src/components/page/meetingList/Filter/Result/index.tsx
src/components/page/meetingList/Filter/Search/Mobile.tsx
src/components/page/meetingList/Grid/Layout.tsx
stitches.config.ts

- close #241 
- 360px 까지는 2줄로 나오게 함.

디바이스에서 리스트를 두줄로 보이길 원함

---

src/components/page/meetingDetail/DetailHeader.tsx
src/components/page/meetingList/Card/index.tsx
src/utils/image.ts

- close #247 
- 플그 팀에서 만든 getResizedImage 함수를 루팡해옴.
- 맛있음. 
- 허나 플그팀에서 어떻게 적용했는지 더 뜯어볼 필요가 있음. 잘 만들어 놓은것 같음.

fix: heic 확장자 대응

---

src/components/page/meetingDetail/DetailHeader.tsx

- close #269 
- 모임 신청을 취소하는 경우에도 23:00부터 가능하다는 안내가 필요합니다.

모임 신청 취소 시 alert 추가

---

pages/index.tsx

- close #271 
- 4월 3일에는 주석 처리한 부분 되돌릴 예정입니다.

모임 개설과 관련된 부분 주석 처리

---

src/api/meeting/hooks.ts

- close #281 
- 슬랙에 올라온 제보 중 하나입니다.

모집 인원 충족 시 처리

---

pages/index.tsx
src/api/meeting/hooks.ts
src/components/page/meetingDetail/DetailHeader.tsx
src/components/page/meetingDetail/RecruitmentStatusList.tsx
src/components/page/meetingList/Grid/Layout.tsx
src/components/page/meetingManagement/ManagementListItem.tsx
src/utils/alertErrorMessage.ts

- close #284 
- alert로 에러 메시지를 안내한 뒤, 상태가 변경되지 않고 아래 이미지처럼 나타나는 문제를 수정했습니다.
- 4/3부터는 모임 개설하기 버튼이 보여야 해서 주석 처리한 코드를 다시 살려놨습니다.
- 슬랙에 들어온 제보를 참고해 Layout.tsx의 margin도 수정했습니다.

모임 승인 시 alert 처리 보완

---

.github/workflows/deploy-development.yml
.github/workflows/deploy-production.yml

배포 github action 수정

---

src/data/categories.ts

모임 생성/수정 시 '행사' 카테고리 선택할 수 있도록 추가

---

src/components/page/meetingList/Filter/Search/Mobile.tsx

- close #314
-  input의 width 값을 명시해줌으로써 사이즈 조절을 하도록함.
- input 의 default width는 20글자

모비일 검색창에 취소가 가려지는 이슈

---

.github/workflows/deploy-development.yml
.github/workflows/deploy-production.yml
next.config.js
package.json
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts
yarn.lock

Sentry 설정 추가

---

src/components/page/meetingDetail/DetailHeader.tsx
src/constants/url.ts
src/hooks/useDisplay.ts

- close #334 
- 전체 회의 때 정했던 분기점으로 수정했습니다.

미디어 쿼리 분기점 수정

---

pages/index.tsx
src/components/page/meetingDetail/DetailHeader.tsx
src/components/page/meetingList/Card/index.tsx
src/components/page/meetingList/Grid/Layout.tsx
src/components/page/meetingList/Pagination.tsx
src/components/tabList/TabList.tsx

- close #336 
확정된 디자인 시스템 수정사항을 반영합니다.

디자인 시스템 수정사항 반영

---

package.json
yarn.lock

플레이그라운드 헤더 패키지 업데이트

---

pages/detail/index.tsx
src/components/page/meetingDetail/FeedPanel.tsx

피드 탭 empty view 추가

---

src/components/page/meetingDetail/InformationPanel.tsx
src/components/page/meetingList/Card/MobileSize/CardType.tsx

간단한 UI 개선사항 반영

---

src/components/page/meetingManagement/ManagementListItem.tsx

- close #366 
텍스트가 영역을 벗어나지 않도록 수정

신청내역 제보 반영

---

src/components/avatar/Avatar.tsx

- close #384 
```tsx
// 샘플 코드
<AvatarGroup>
<Avatar />
<Avatar />
<Avatar Overlay={<Dimmed>+</Dimmed>} />
</AvatarGroup>
```

Avatar 컴포넌트 Overlay 인터페이스 추가

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

피드 상세 뷰어 컴포넌트 스타일링 - 콘텐츠 영역

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

피드 상세 댓글 좋아요 영역 추가

---

pages/index.tsx
src/components/tabList/TabList.tsx

- close #390 
https://github.com/sopt-makers/sopt-crew-frontend/assets/26538967/8dfb7a87-460f-4fe4-8278-0fb6cac7d4dd

feat: tab의 생명력을 앗아가다!

---

pages/detail/index.tsx
src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx

피드 생성 폼 컨펌 모달 적용 및 formController 적용

---

pages/detail/index.tsx
src/api/post/index.ts
src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx

피드 생성 api 를 연결 해보자

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

- close #401 
- 댓글 부분과 좋아요 부분을 하나의 div 로 감싸주고, width 를 지정해 줌으로써 댓글 및 좋아요 수에 관계없이 내용이 중앙 정렬되게 해주었습니다. 

피드 상세 댓글 좋아요 영역 UI 구현 방식 수정과 모바일 대응

---

src/components/seo/SEO.tsx

- close #425 
- '/group'이 빠져서 404가 뜨고 있었어요 🥲

og:image가 안 보이는 문제

---

pages/detail/index.tsx
src/components/page/meetingDetail/Feed/EmptyView.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx

- 다시 피드가 기본 값으로 설정되어 보이도록 수정했어요.
- 작성하러 가기 버튼을 누르면 재훈 오빠가 구현한 모달이 뜨도록 수정했어요.

배포를 위해 주석 처리하거나 제거했던 코드 되살리기

---

package.json
src/components/page/meetingDetail/Feed/FeedPanel.tsx
yarn.lock

- close #447 
- @egjs/react-infinitegrid로 masonry 레이아웃을 적용했어요.

masonry 레이아웃 적용

---

src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx

- close #459 
- 공통 컴포넌트 ConfirmModal 를 이용해서 삭제 모달 컴포넌트 ui 추가하는 간단한 작업 완료했습니당

style: 댓글 삭제 모달 컴포넌트 추가

---

pages/post/index.tsx
src/api/post/hooks.ts
src/components/feed/FeedActionButton/FeedActionButton.tsx
src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx

피드 상세 뷰 댓글 액션 합성할 수 있도록 수정

---

src/components/feed/Modal/FeedCreateModal.tsx
src/components/feed/Modal/FeedEditModal.tsx

모바일 주소창으로 인해 완료버튼 안보이는 이슈

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

게시글 상세 뷰 모바일 스타일 적용

---

pages/post/index.tsx

피드 상세 뷰 가운데 중앙 정렬

---

src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
src/components/feed/FeedPostViewer/FeedPostViewer.tsx

- close #495 
- 카드뷰에서는 짤릴가능성도 있고 이미 클릭이벤트도 있기에 적용 안함

[제안 01] 피드 게시글 내 링크 하이퍼링크 기능 추가 

---

pages/post/index.tsx

- close #509 
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/d091dea5-5a80-4095-8a8c-ad6ea7be0b96

피드 상세 뷰 수정 기능 연동

---

src/components/feed/FeedCommentInput/FeedCommentInput.tsx

comment input color change

---

src/components/feed/Modal/FeedFormPresentation.tsx

[이슈 22] 피드 작성, 수정 모바일 뷰 타이틀 밑에 스트로크 제거 

---

pages/post/index.tsx
src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx

- close #487 
isMine={comment.user.id === me?.id} >> me.id 를 getPost 의 user.id 로 변경

[이슈 14] 댓글 글쓴이 판별하는 변수, isMine 수정

---

src/components/page/meetingList/Card/DesktopSizeCard.tsx

group category border color change

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

하단에 여백 없는 것 수정

---

pages/post/index.tsx
src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx

댓글 작성한 사람이 게시글 작성한 사람인지 확인하는 로직 수정

---

src/components/feed/FeedCommentInput/FeedCommentInput.tsx

- close #520 
https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/834f2152-7b79-4ac2-bbbe-b8bc9710d74f

피드 댓글 입력 UI 자동 리사이즈 기능 추가

---

src/components/page/meetingDetail/Feed/FeedItem.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx

[이슈 15] mo뷰 카드 간 스페이싱에 그레이가 밝게 들어가는데 없음

---

src/utils/dayjs.ts

시간 표기해주는 형식 수정

---

src/components/feed/Modal/FeedFormPresentation.tsx

피드 작성,수정뷰 x 아이콘에 cursor:pointer 추가

---

src/components/page/meetingDetail/Feed/FeedItem.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx

피드 리스트 앰플리튜드 로깅

---

pages/post/index.tsx
src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
src/components/feed/FeedCommentInput/FeedCommentInput.tsx

앰플리튜드 이벤트 로깅 수정

---

pages/detail/index.tsx

모집마감은 피드 탭부터 뜨도록 수정

---

src/components/page/meetingDetail/Feed/FeedItem.tsx

피드 아이템 스타일 이슈

---

src/components/modal/ImageCarouselModal.tsx

주소창에 가려지는 스타일 이슈

---

src/components/page/meetingManagement/ManagementListItem.tsx

- close #548 
- stitches 이슈들
- https://github.com/stitchesjs/stitches/issues/1039
- https://github.com/stitchesjs/stitches/issues/913
| Before | After |
|-----|-----|
|  <img width="409" alt="Screenshot 2023-10-03 at 1 08 37 AM" src="https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/e5d38874-c2ff-4f29-962a-402f1aae6878">  |   <img width="409" alt="Screenshot 2023-10-03 at 1 07 40 AM" src="https://github.com/sopt-makers/sopt-crew-frontend/assets/31213226/17dd9be1-7b63-421f-b203-e5722443e29a"> |

신청자 관리 화면 스타일 이슈 수정

---

src/components/page/meetingDetail/Feed/FeedItem.tsx

피드 아이템 프로필 링크 이슈

---

src/components/page/meetingDetail/Information/InformationPanel.tsx
src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx

링크가 영역 벗어나는 이슈 해결

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

링크가 화면을 벗어나지 않도록 word-break 속성 지정

---

pages/index.tsx
pages/make/index.tsx
pages/mine/index.tsx
pages/mine/management/index.tsx
src/ampli/index.ts
src/components/disclosure/Disclosure.tsx
src/components/feed/FeedPostViewer/FeedPostViewer.tsx
src/components/page/meetingDetail/Carousel/NextArrow.tsx
src/components/page/meetingDetail/Carousel/index.tsx
src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
src/components/page/meetingDetail/MeetingController/index.tsx
src/components/page/meetingList/Card/ManagementButton.tsx
src/components/page/meetingList/Card/index.tsx
src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
src/components/page/meetingList/Filter/Modal/Chip/index.tsx
src/components/page/meetingList/Filter/Modal/OpenButton.tsx
src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
src/components/page/meetingList/Pagination.tsx
src/components/page/meetingManagement/ManagementListItem.tsx

- close #552 
- 전부 반영 완료했습니다~!

앰플리튜드 로깅 작업

---

pages/_app.tsx
src/components/page/meetingDetail/Feed/Skeleton/FeedItemSkeleton.tsx
stitches.config.ts

- close #600 
- 새로운 피드 뷰 대응하면서 breakpoint 가 추가된 것 반영했어요
- desktop breakpoint는 별 의미가 없어서 제거해요.

breakpoint 수정

---

pages/list/index.tsx
src/ampli/index.ts
src/components/feed/Modal/FeedCreateModal.tsx
src/components/page/meetingDetail/Feed/FeedItem.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx

- close #599 
- 플로팅 버튼처럼 아직 개발되지 않은 부분에 대해서는 앰플리튜드를 연결하지 않았어요.
잊지 않고 배포 전에 추가하겠습니다~!

12/08 배포 건에 대한 앰플리튜드 신규 이벤트 대응

---

src/api/post/index.ts
src/components/feed/Modal/FeedCreateModal.tsx
src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
src/components/feed/Modal/FeedEditModal.tsx
src/components/feed/Modal/FeedFormPresentation.tsx
src/components/feed/Modal/SelectMeeting/SelectMeetingOptionItem.tsx
src/components/feed/Modal/SelectMeeting/index.tsx
src/components/feed/Modal/feedSchema.ts

- close #605 
- FeedCreateWithSelectMeetingModal 이거 이름 추천 받아요...
-  FeedFormPresentation 에서 분기처리 하면서 확장했음. 일단 그렇게 했음... 뭐... 더 확장 안되겠지
https://github.com/sopt-makers/sopt-crew-frontend/assets/26538967/8fecf2d1-21cb-455d-92f2-7ef760059ddc

플로팅버튼에 들어갈 피드 생성 뷰 제작

---

pages/index.tsx
src/__generated__/schema.d.ts
src/api/post/hooks.ts
src/api/post/index.ts
src/api/user/index.ts
src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
src/components/modal/FloatingButtonModal.tsx
src/components/modal/NoJoinedGroupModal.tsx
src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx
src/components/page/meetingDetail/Feed/FeedItem/index.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx
src/components/page/postList/FloatingButton/index.tsx

- close #612 
- getPosts api 에 meetingId를 선택적으로 받을 수 있게 작업을 해야합니다. 
- 그리고 그에 수반하는 useInfinitePosts도 meetingId 를 optional 로 받을 수 있게 작업되야하고, 다른쓰는곳에서 사이드이펙트가 없는지 확인해야합니다.
- 내가 속한 모임 api 가 나오면 FeedCreateWithSelectMeetingModal 의 mock 데이터를 삭제해야합니다.
- 내가 속한 모임이 없을떄는 현수가 제작한 모임이 없다는 모달이 떠야하는것으로 분기 처리 해야합니다.
- 뒤를 맡깁니다

플로팅 버튼 action 연결 및 api 연결

---

src/components/util/auth.ts

- close #619 
- `.env.local` 파일 만들어서 환경 변수에 본인 토큰 넣어주세용

개발 환경에서 인증 토큰을 환경 변수로 관리하도록 수정

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx

피드 상세페이지 스타일 이슈 수정

---

src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
src/components/page/meetingDetail/Feed/FeedItem/index.tsx

mockData 를 안뺏지뭐에요???

---

pages/mine/index.tsx

내모임 클릭이 이상하요

---

src/hooks/useScrollRestoration.ts

스크롤 위치 blacklist 추가

---

src/components/feed/Modal/SelectMeeting/SelectMeetingOptionItem.tsx
src/components/feed/Modal/SelectMeeting/index.tsx
src/components/modal/FloatingButtonModal.tsx
src/components/page/postList/FloatingButton/index.tsx

피드개설 디자인 이슈 해결

---

src/components/feed/Modal/FeedFormPresentation.tsx

margin-left 맞추기

---

pages/index.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx

같은놈을 여러번 찌르네요?

---

src/components/modal/FloatingButtonModal.tsx

아이폰 스타일 이슈 대응

---

pages/index.tsx
src/components/page/meetingDetail/Feed/FeedPanel.tsx

- close #654
-  높이를 넣었다가 둠칫대는것을 봄
- 없애봐도 되긴하더라
- 근데 최소한 1px 은 있어야 제대로 작동하더라
- 1px 도 둠칫하더라
- 그래서 ref 안적힌 애도 1px 줘서 분기함

oberverTarget의 height는 없어도 되자나요? 

---

pages/index.tsx

앰플리튜드 로깅 추가

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx
src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx

스터디, 행사 텍스트 컬러 다르게 적용

---

pages/index.tsx
src/api/post/hooks.ts
src/components/page/meetingDetail/Feed/Skeleton/DesktopFeedListSkeleton.tsx

- close #664 
|데스크탑|모바일|
|:-:|:-:|
|<video src="https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/de5304c2-4757-4ac7-84a6-d1d2246bd1e8" />|<video src="https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/b3d9c507-01dc-438b-8565-e7c5a9e98224" />|

모임 피드 첫 로딩 시 스켈레톤 뜨도록 수정

---

src/components/feed/FeedCommentInput/FeedCommentInput.tsx
src/components/feed/Modal/FeedFormPresentation.tsx

사파리 줌인 이슈 대응

---

src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx

fix: applicantCount 와 approvedUserCount 뒤바뀜 문제 픽스

---

.github/CODEOWNERS
.github/workflows/AutomaticAssignReviewer.yml

docs: 코드 리뷰어 멤버 변경

---

package.json
pages/post/index.tsx
src/__generated__/schema.d.ts

swagger spring 문서 타입 추가 및 api 엔드포인트 변경

---

public/assets/svg/GroupBrowsingCardSeparator.svg
src/api/meeting/index.ts
src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx

사소한 디자인 QA 및 활동 기간 api 수정

---

pages/_app.tsx

프로덕션 배포 에러 수정 : useEffect 의존성 배열 수정

---

pages/_app.tsx

Reverts sopt-makers/sopt-crew-frontend#714

Revert "콘솔 추가 프로덕션 배포"

---

src/components/page/meetingDetail/MeetingController/index.tsx

모임 신청 중 에러 발생 시, alert에 에러 메시지 표시

---

src/components/modal/ConfirmModal.tsx
src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
src/components/page/meetingDetail/MeetingController/index.tsx

feat: 모임 신청,취소하기 로더 UI추가 및 alert창 추가

---

src/components/page/meetingDetail/MeetingController/index.tsx

모임 신청하는 중 onError 상황에서 refetchQueries 추가

---

pages/mine/management/index.tsx

신청자 관리 페이지에 홈 버튼 추가

---

src/components/feed/FeedPostViewer/FeedPostViewer.tsx
src/components/page/meetingDetail/Feed/FeedItem/index.tsx

피드 작성 시간 표기 정상화

---

.github/workflows/deploy-development.yml
.github/workflows/deploy-production.yml

깃허브 빌드 세팅 변경

---

package.json
pages/_app.tsx
pages/post/index.tsx
src/components/feed/FeedPostViewer/FeedPostViewer.tsx
src/components/feed/Modal/FeedCreateModal.tsx
src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
src/components/feed/Modal/FeedFormPresentation.tsx
yarn.lock

- close #750 
- 액션 버튼에서 router.push를 할 때 계속 /group~ 이 붙어져서... window객체를 활용해서 baseURL을 가져와서 dev, prod분류해서 넣어뒀습니다.
- ... 이번에 새로운 노트북에서 작업을 해서 저번에 현수가 yarn upgrade했던거... 다시 yarn 해줬더니 또 yarn.lock 파일이 난리가 난 것 같기도 해서.. 요 부분 문제 없는지 한 번 확인해주실 수 있을까요? ㅜ . ㅜ...

Feat/#750 모임 피드 작성 시 플그 리다이렉션 액션 토스트 구현

---

src/components/feed/Modal/FeedCreateModal.tsx

- close #767 
- 동일한 기능을 하는 코드가 여러 곳에 산재되어 있어서 이런 예외가 발생한 것 같아요. 나중에 하나의 컴포넌트로 합치는 작업을 해도 좋을 것 같습니다 ~!

feat: 내 모임에서 피드 작성 시 useThrottle 적용

---

src/ampli/index.ts
src/components/feed/Modal/FeedCreateModal.tsx
src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx

- close #771 
앰플리튜드 처음 붙여보는데... 사실 이게 맞는지 모르겠습니다.... 
1. 앰플리튜드 사이트에서 이벤트 추가 등록하고,
2. `ampli pull web`해서 받아온 다음에
3. 클릭 이벤트에 ampli.clickfeedshared() 함수 작성
이렇게 하는게 맞을까요....? ^^..  로컬에서 이벤트 잘 붙여진건지 체크하는건 어떻게 하는건가요 ...ㅠ . ㅜ ...? 방법이 없을까요?

feat: 공유하러 가기 버튼 amplitude 이벤트 추가

---

src/components/feed/FeedCommentInput/FeedCommentInput.tsx
src/components/feed/Mention/index.tsx

멘션 기능 Safari 및 모바일 스타일링 이슈 fix

---

pages/post/index.tsx

댓글 작성 api 스펙 변경에 따른 업그레이드

---

packages/react-mentions/dist/react-mentions.cjs.dev.js
packages/react-mentions/dist/react-mentions.cjs.prod.js
packages/react-mentions/dist/react-mentions.esm.js

QA: 모바일에서 멘션 삭제 시 글자 남아있는 이슈 수정

---

packages/react-mentions/dist/react-mentions.cjs.dev.js
packages/react-mentions/dist/react-mentions.cjs.prod.js
packages/react-mentions/dist/react-mentions.esm.js

모바일 이슈 원인 파악

---

packages/react-mentions/dist/react-mentions.cjs.dev.js
packages/react-mentions/dist/react-mentions.cjs.prod.js
packages/react-mentions/dist/react-mentions.esm.js
src/components/feed/Mention/index.tsx

정공법이 아닌 방식으로 했더니.. 문제가 더 커지는 군요... 결국 롤백행..ㅠㅠ

Revert "QA: React-Mentions 의 appendSpaceOnAdd 기능으로 모바일에서 멘션 delete 시 글자 남아있는 이슈 해결"

---

src/components/feed/Mention/index.tsx

Suggestion 밑에 공간이 충분히 있지 않을 시, Suggestion 을 커서 위로 올리기

---

src/components/feed/Mention/index.tsx

QA: 모바일 기기에서만 suggestionAboveCursor

---

src/components/feed/Mention/index.tsx

QA: 댓글에서만 suggestionAbove 허용

---

pages/index.tsx
public/assets/svg/group_browsing_arrow_left.svg
src/components/groupBrowsing/Carousel/NextArrow.tsx
src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx

모임 둘러보기 기능 스타일링 추가 (그라데이션)

---

pages/index.tsx

style: 그라데이션 요소 적용 케이스 축소

---

src/components/page/meetingDetail/Feed/FeedItem/index.tsx

- close #815 
wsrv 에서 간헐적으로 발생하는 에러로 인해 최신피드 렌더링 속도가 매우 느려지는 문제 hot fix 

wsrv 에러 hotfix

---

src/components/page/meetingList/Advertisement/index.tsx
src/hooks/useScrollRestoration.ts

광고 구좌 모바일 QA

---

pages/_app.tsx
pages/post/index.tsx
src/__generated__/schema2.d.ts
src/api/API_LEGACY/user/hooks.ts
src/api/API_LEGACY/user/index.ts
src/api/post/hooks.ts
src/api/post/index.ts
src/components/feed/FeedPostViewer/FeedPostViewer.tsx

- close #847 
- 혹시 마이그레이션 더 해야될 api 있으면 해당 브랜치에 계속해서 작업하겠습니다 !!
200 받은 거 확인했습니다!

API 마이그레이션

---

pages/post/index.tsx
src/__generated__/schema2.d.ts
src/components/blocker/CommentBlocker.tsx
src/components/blocker/ContentBlocker.tsx
src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
src/components/feed/FeedCommentViewer/FeedCommentViewer.stories.ts
src/components/page/meetingDetail/Feed/FeedPanel.tsx
src/components/page/meetingList/Advertisement/index.tsx
src/components/page/meetingList/Card/DesktopSizeCard.tsx

피드홈/피드상세/모임상세/댓글/대댓글 차단된 컨텐츠 UI + API 연결

---

src/components/blocker/CommentBlocker.tsx

fix: writing 수정

---

package.json
pages/make/index.tsx
src/__generated__/schema2.d.ts
src/api/API_LEGACY/meeting/index.ts
src/api/index.ts
src/components/form/Presentation/index.tsx
src/components/form/Textarea/index.tsx
src/types/form.ts

모임 개설 시 "개설자 소개" 선택 입력으로 변경 + POST meeting/v2 api 마이그레이션 + dev 서버 url 임시로 변경

---

src/components/form/Calendar/index.tsx
src/components/form/FileInput/index.tsx
src/components/form/Label/index.tsx
src/components/form/Presentation/index.tsx

모임 개설 디자인 QA 반영

---

src/components/form/Calendar/index.tsx

캘린더 일요일부터 시작

---

src/api/index.ts
src/components/page/meetingList/Advertisement/AdCarousel.tsx
src/components/page/meetingList/Advertisement/index.tsx
src/components/page/meetingList/Grid/List.tsx

advertisements 필드 null 값 예외 처리

---

src/components/form/Calendar/index.tsx
src/components/form/FileInput/index.tsx
src/components/form/Select/BaseSelect/BaseSelect.tsx
src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
src/components/form/Select/Button/index.tsx
src/components/form/TextInput/index.tsx
src/components/form/Textarea/index.tsx

- close #890
https://github.com/user-attachments/assets/96afc1df-bc1b-4a28-a4a3-1e4bb2cdc012

mds color와 통일

---

pages/edit/index.tsx
src/components/form/Presentation/index.tsx

- close #892 
https://github.com/user-attachments/assets/2d67065f-4935-4c18-8e30-af654300a487

모집 대상, 모임장 소개 모바일 반응형 + 모임 수정 배경색 변경

---

src/api/API_LEGACY/meeting/index.ts
src/components/feed/Modal/FeedFormPresentation.tsx
src/components/form/Presentation/index.tsx

모임 상세 조회 API 마이그레이션 배포

---

pages/edit/index.tsx
src/__generated__/schema2.d.ts

Reverts sopt-makers/sopt-crew-frontend#901

Revert "getmStartDate -> mStartDate"

---

pages/edit/index.tsx
src/__generated__/schema2.d.ts
src/api/API_LEGACY/meeting/hooks.ts
src/api/API_LEGACY/meeting/index.ts
src/api/API_LEGACY/user/index.ts
src/api/post/index.ts
src/components/page/meetingDetail/Carousel/index.tsx
src/components/page/meetingDetail/Information/InformationPanel.tsx
src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
src/components/page/meetingDetail/MeetingController/index.tsx
src/components/page/meetingManagement/MeetingInformation.tsx

모임상세조회 API 배포

---

src/components/form/TextInput/index.tsx
src/components/page/meetingDetail/Information/InformationPanel.tsx
src/constants/option.ts

Input 높이 및 모집 대상 chip 변경

---

src/components/feed/Modal/FeedFormPresentation.tsx

fix: 웹뷰 피드 작성 remainingHeight 변경

---

src/__generated__/schema2.d.ts
src/api/API_LEGACY/meeting/hooks.ts
src/api/API_LEGACY/meeting/index.ts
src/components/page/meetingDetail/MeetingController/index.tsx

매크로 방지를 위한, 행사 신청 / 일반 모임 신청 API 분리

---

src/api/API_LEGACY/meeting/hooks.ts
src/api/API_LEGACY/meeting/index.ts
src/api/auth/index.ts

Reverts sopt-makers/sopt-crew-frontend#953

Revert "API 마이그레이션 마무리"

---

src/api/API_LEGACY/meeting/hooks.ts
src/api/API_LEGACY/meeting/index.ts

- close #960 
- 지난번에 코드리뷰 받았던 것 중, 오류가 있었던 `me` 제외한 부분 옮겨두었습니다! dev 반영 바로 하겠습니다:)

me 제외 API 마이그레이션

---

pages/make/bungae/index.tsx
src/api/meeting/index.ts
src/components/form/Bungae/index.tsx
src/components/modal/FloatingButtonModal.tsx
src/data/options.ts
src/types/form.ts

- close #979 
- label: value: 가 있는 객체, 왜 저렇게 설계했지? label 과 value 가 같은데... 라고 생각하실 수 있을 것 같아요. 데이터의 변경 가능성 때문에 프론트와 서버 코드를 분리하는 것이 안전하다고 생각하여 이렇게 설계하였습니다~

번쩍 개설 API 연결 작업

---

src/components/page/list/Card/DesktopSizeCard/constant.ts

style: 마무리

---

src/components/page/home/HomeCardList/index.tsx

feat: 모임 바꿈

---

pages/list/index.tsx
src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
src/components/page/detail/Information/constant.tsx
src/components/page/list/Card/DesktopSizeCard/constant.ts

협의 후 노출 표시

---

pages/index.tsx
src/components/groupBrowsing/Carousel/Carousel.tsx
src/components/groupBrowsing/Carousel/NextArrow.tsx
src/components/page/detail/Carousel/NextArrow.tsx
src/components/page/detail/Carousel/index.tsx
src/components/page/home/HomeCardList/CardList.tsx
src/components/page/home/QuickMenu/index.tsx

- close #1030 
https://github.com/user-attachments/assets/bde289b4-5219-41d4-929e-285af1b69618

모임홈 반응형 적용

---

src/api/auth/index.ts

feat: auth/v2 마이그레이션

---

src/api/auth/index.ts
src/api/index.ts

auth API header 제거

---

.github/CODEOWNERS
.github/workflows/AutomaticAssignReviewer.yml
src/components/groupBrowsing/Carousel/Carousel.tsx
src/components/groupBrowsingSlider/groupBrowsingSlider.tsx

모임홈 반응형 QA 반영

---

src/components/form/Presentation/index.tsx

공식일정 툴팁 및 다이얼로그 텍스트 변경

---

src/components/page/home/HomeCardList/DesktopCard.tsx
src/components/page/list/Card/DesktopSizeCard/index.tsx
src/components/page/list/Card/MobileSize/CardType.tsx
src/components/page/list/Card/MobileSize/ListType.tsx
src/utils/image.ts

- close #1056 
rebase 를 이용해서 불필요한 커밋을 제거한 후, 이미지 리사이징 커밋만 프로덕션 배포하기 위한 PR 입니다!
혹시라도 롤백을 해야할 가능성도 있어서, 이미지 리사이징 커밋 exclusive pr 을 만드는 것이 좋아보여 이렇게 진행합니다!

이미지 리사이징 프로덕션 배포를 위한 PR

---

src/components/page/home/HomeCardList/DesktopCard.tsx
src/components/page/list/Card/DesktopSizeCard/index.tsx
src/components/page/list/Card/MobileSize/CardType.tsx
src/components/page/list/Card/MobileSize/ListType.tsx
src/utils/image.ts

Revert "이미지 리사이징 프로덕션 배포를 위한 PR"

---

src/__generated__/schema2.d.ts
src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx

- close #1046 
원래 모바일이었을 때도 2열을 유지하던 뷰였는데요! 이번에 모바일일 때 1열로 바뀌는 뷰로 개편되면서, `flex` 보다는 `grid` 가 더 적합하다고 판단하여 스타일 코드를 많이 쳐냈습니다! 단순 뷰 작업이라 리뷰포인트가 많이 없어보이네용 !!
https://github.com/user-attachments/assets/84b80913-e4df-48c2-a214-dbab532d716e

모집 현황 신청자 넘버링

---

src/components/Tag/RecruitmentStatusTag.tsx
src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx

환영 Tag, 모집 상태 Tag 디자인 개선

---

src/components/Tag/RecruitmentStatusTag.tsx
src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx

- close #1061 
- 단순 fontSize 수정이라 리뷰 생략하겠습니다!

Tag 폰트 크기 수정

---

src/components/groupBrowsing/mobileSizeCard.tsx
src/components/page/home/HomeCardList/DesktopCard.tsx
src/components/page/home/HomeCardList/MobileCard.tsx
src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
src/components/page/list/Card/DesktopSizeCard/index.tsx

카테고리명 안 보이는 이슈 핫픽스 배포

---

src/components/page/home/HomeCardList/DesktopCard.tsx

fix: width 잘못 설정되어 이미지 흐리게 보이는 이슈 수정

---

src/components/page/home/HomeCardList/index.tsx

- close #1075 
- 단순 상수 변경이라 리뷰없이 머지합니다.

모임홈 Editable Content 변경

---

pages/_app.tsx

refresh token 로직 추가 배포

---

pages/_app.tsx

- close #1083 
- @hoonyworld 요청

dev 토큰 갱신 시간 2분 설정

---

pages/_app.tsx
src/ampli/index.ts

- close #1085 
- amplitude 붙이는 바

사용자 해상도 ampli 추가

---

pages/mine/management/index.tsx
src/components/form/SearchMention/index.tsx
src/components/form/TableOfContents/index.tsx
src/components/page/list/Grid/List.tsx

- close #issue_number
- 단순 순서 방식 변경이라 리뷰없이 머지합니다!

신청자 리스트 순서 방식 변경

---

pages/mine/management/index.tsx
src/components/page/mine/management/ManagementListItem.tsx

- close #1091 
- query 부분은 추후 리팩토링 예정입니다!

신청자 리스트 QA 반영

---

package.json
yarn.lock

- close #1094 
@sopt-makers/playground-common 버전 업데이트 적용했습니다!
[AS-IS]
[TOBE]

@sopt-makers/playground-common 버전 업데이트

---

src/components/modal/DefaultModal.tsx
src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
src/components/page/detail/MeetingController/index.tsx

- close #1096 
- 단순 style 변경입니다!
https://github.com/user-attachments/assets/b52d7e49-9eda-498f-aa49-7bebd22a0f2e

신청 현황 모달 QA 반영

---

src/components/modal/DefaultModal.tsx
src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
src/components/page/detail/MeetingController/index.tsx

신청 현황 모달 QA 반영 배포

---

package.json
src/api/API_LEGACY/meeting/index.ts
src/components/page/list/Filter/DropDown/index.tsx
src/components/page/list/Filter/Reset/index.tsx
src/components/page/list/Filter/index.tsx
yarn.lock

- close #1045
**[ 리렌더링으로 인한 필터 연속 선택 불가 이슈 ]**
이전에 필터 기능이 쿼리 파라미터 기반으로 동작하고 있어서, 선택 시 URL이 변경되면서 페이지가 다시 로드되는 구조입니다. 
이로 인해 드롭다운이 매 선택마다 닫히는 깜빡임 이슈가 발생하고 있습니다.
UX 가 좋지 않을 것 같아서, 우선 임시 조치로 debounce를 적용해 1.3초정도 임시로 정해서 그 후에 URL이 변경되도록 처리한 상태입니다.
해결 방향에 대해 슬랙을 통해 PD 분들께 의견을 요청드린 상황입니다!
만약 이 기능을 개선해야 할 경우 구조적인 변경이 필요하여 리소스 좀 더 필요할 것으로 예상됩니다
https://github.com/user-attachments/assets/c73325c6-c3fe-4554-80b9-847d0c3a7412

[Feat/#1045] 다중 필터 기능 적용

---

src/__generated__/schema2.d.ts
src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx
src/components/page/list/Card/DesktopSizeCard/constant.ts
src/components/page/list/Card/DesktopSizeCard/index.tsx
src/data/options.ts

- close #1107 
- 단순 UI 변경이었습니다!
- `UsersIcon` 못 넣은 이슈는 슬랙에 공유드렸어요!

키워드 추가 마무리

---

src/api/API_LEGACY/meeting/index.ts

- close #1121
page 값 전달 안 되고 있었네요, 추가했습니다!

페이지네이션 이슈 핫픽스

---

src/api/API_LEGACY/meeting/hooks.ts
src/api/API_LEGACY/meeting/index.ts

- close #1119
[SLACK] https://sopt-makers.slack.com/archives/C050DQPCS4A/p1747584447883549
핫픽스로 필터 오류 수정합니다.

isOnlyActiveGeneration 필터 오류 HOTFIX

---

src/api/API_LEGACY/meeting/hooks.ts
src/api/API_LEGACY/meeting/index.ts

모임 필터링 관련 핫픽스 배포

---

src/components/page/detail/Information/constant.tsx

- close #1124 
- 단순 style 수정입니다
https://github.com/user-attachments/assets/31632d1e-5076-4707-b3e1-8a3e80fcbbce

모임 상세 페이지에서 환영 태그 disabled 처리

---

src/components/page/list/Filter/DropDown/index.tsx

- close #1126
시간 조정만 했습니다~! 
https://github.com/user-attachments/assets/d6de3ba5-4340-417c-af13-2490d3f6bd31

전체모임 다중필터 debounce 시간 조정

---

pages/index.tsx
src/api/property/hooks.ts
src/api/property/index.ts
src/components/page/home/HomeCardList/CardList.tsx
src/components/page/home/HomeCardList/index.tsx

- close #1109
- 왜 key로 param 넣었는데 key로 다시 접근하냐함은.. api 명세입니다 ..

Editable Contents API 연결

---

pages/index.tsx
src/api/property/hooks.ts
src/api/property/index.ts
src/components/page/detail/Information/constant.tsx
src/components/page/home/HomeCardList/CardList.tsx
src/components/page/home/HomeCardList/index.tsx
src/components/page/list/Filter/DropDown/index.tsx

Reverts sopt-makers/sopt-crew-frontend#1137
서버 배포 안 한거 또 까먹음 ..

Revert "v1.0.0"

---

pages/index.tsx
pages/list/index.tsx
src/api/post/hooks.ts
src/api/user/hooks.ts
src/api/user/index.ts
src/components/GuideButton/index.tsx
src/components/KeywordsSettingButton/index.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/TooltipClose.tsx
src/components/Tooltip/TooltipContent.tsx
src/components/modal/AlarmSettingModal.tsx
src/components/page/list/Alarm/BottomSheet/AlarmSettingBottomSheet.tsx
src/components/page/list/Alarm/Modal/AlarmSettingModal.tsx
src/data/options.ts

- close #1128
유저 관심 키워드 기능 구현했습니다. 
반응형 개선 작업 후에 하려고 했던 건데, 
반응형 작업이 반영이 안 된 상태라, 이전 breakpoint 가 적용되어 있습니다. 
반응형 전역 이슈를 먼저 반영하고, 추후 다시 반응형만 개선될 수 있음을 말씀 드립니다! 
https://github.com/user-attachments/assets/098aa6ba-a092-48c6-96f3-d9082a93df17

[Feat] 유저 관심 키워드(알림 설정) 기능 구현

---

src/components/page/list/Card/DesktopSizeCard/constant.ts
src/components/page/list/Card/DesktopSizeCard/index.tsx

[Feat] MeetingInformation에 isValid 로직 추가

---

src/ampli/index.ts
src/components/page/list/Filter/DropDown/index.tsx

- close #1116
총 5가지 프로퍼티 연결했습니다. 
값은 value 를 join 해서 string 형태로 들어갑니다. 
1. 카테고리 
2. 키워드
3. 활동기수 여부
4. 모임 상태 
5. 파트

[Feat] 다중필터 amplitude 연결

---

.github/workflows/AutomaticAssignReviewer.yml
src/api/post/PostQueryKey.ts
src/api/post/mutation.ts
src/domain/home/HomeCardList/DesktopCard.tsx
src/domain/home/HomeCardList/MobileCard.tsx
src/shared/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx

main << develop
